### Introduction to Pandas............           [RECORDED]

In [1]:
import pandas as pd

In [2]:
ls


 Volume in drive C is OS
 Volume Serial Number is 1600-9EB4

 Directory of C:\Users\santa

14-03-2023  17:07    <DIR>          .
22-09-2022  14:03    <DIR>          ..
22-08-2022  12:19    <DIR>          .anaconda
08-02-2023  16:31    <DIR>          .conda
22-08-2022  12:19                25 .condarc
22-08-2022  12:18    <DIR>          .continuum
07-03-2023  12:25                58 .gitconfig
20-02-2023  11:11                53 .git-for-windows-updater
10-07-2022  18:25    <DIR>          .idlerc
14-03-2023  11:35    <DIR>          .ipynb_checkpoints
22-08-2022  13:10    <DIR>          .ipython
22-08-2022  14:04    <DIR>          .jupyter
14-03-2023  12:17    <DIR>          .matplotlib
27-08-2022  08:26                43 .python_history
27-02-2023  14:06               527 .vivaldi_reporting_data
04-01-2023  10:28    <DIR>          .vscode
17-02-2023  14:53    <DIR>          __pycache__
14-03-2023  12:07             1,173 addresses.csv
14-03-2023  12:55            32,256 airline1.xls
18-

In [3]:
pd.read_csv('test10.csv')

Unnamed: 0     a       b      c       d      e      f
0            0  1961   5.465  0.460  0.3079  3.122  1.736
1            1  1962   5.825  0.485  0.3783  3.184  1.926
2            2  1963   6.876  0.506  0.4180  3.263  2.041
3            3  1964   7.823  0.538  0.5163  3.412  1.997
4            4  1965   9.120  0.564  0.5879  3.623  2.257
5            5  1966  10.512  0.586  0.5369  4.074  2.742
6            6  1967  13.020  0.622  0.4443  4.710  3.564
7            7  1968  15.261  0.666  0.3052  5.217  4.767
8            8  1969  16.313  0.731  0.2332  5.569  6.511
9            9  1970  16.002  0.831  0.1883  5.495  7.627
10          10  1971  15.876  0.906  0.2023  5.334  8.673
11          11  1972  16.662  1.000  0.2506  5.345  8.331
12          12  1973  17.014  1.056  0.2668  5.662  8.557
13          13  1974  19.305  1.131  0.2664  5.729  9.508
14          14  1975  18.721  1.247  0.2301  5.722  9.062

In [5]:
pd.read_excel(r"C:\Users\santa\Downloads\Excel Formulas Masterclass - Students (1).xlsx")

Text Based Formulas                  Unnamed: 1  \
0                        NaN  Makes everything uppercase   
1             Employee Names                       UPPER   
2          raHul    sHah               RAHUL    SHAH       
3           Payal MEHta                 PAYAL MEHTA        
4             Rita ShaH                   RITA SHAH        
5                Neha mishra                 NEHA MISHRA   
6               tanVi Sharma                TANVI SHARMA   
7               kanci NagoRI                KANCI NAGORI   
8                RahUl  shAh                 RAHUL  SHAH   
9                PaYal mehta                 PAYAL MEHTA   
10           RitA     Mishra             RITA     MISHRA   
11             neha   mishra               NEHA   MISHRA   
12              Tanvi Sharma                TANVI SHARMA   
13       Kanci        Nagori         KANCI        NAGORI   
14              HarShit shah                HARSHIT SHAH   
15               mehuL mehta                 MEHUL MEHTA   
16                bhumi shah                  BHUMI SHAH   
17             riYA SangHavi               RIYA SANGHAVI   
18              MaNish DeSai                MANISH DESAI   
19           Hitendra   Khan             HITENDRA   KHAN   
20             Bharat Kapoor               BHARAT KAPOOR   
21               Dipesh Shah                 DIPESH SHAH   
22             KanaN somaiya               KANAN SOMAIYA   
23              KarAN Kapoor                KARAN KAPOOR   
24                Tina mEhta                  TINA MEHTA   
25              Krystal Shah                KRYSTAL SHAH   
26                Kirit Khan                  KIRIT KHAN   
27              Kushal Desai                KUSHAL DESAI   

                    Unnamed: 2                            Unnamed: 3  \
0   Makes everything lowercase  Capitalize first letter of each word   
1                        LOWER                                PROPER   
2            rahul    shah                         Rahul    Shah       
3             payal mehta                           Payal Mehta        
4               rita shah                             Rita Shah        
5                  neha mishra                           Neha Mishra   
6                 tanvi sharma                          Tanvi Sharma   
7                 kanci nagori                          Kanci Nagori   
8                  rahul  shah                           Rahul  Shah   
9                  payal mehta                           Payal Mehta   
10             rita     mishra                       Rita     Mishra   
11               neha   mishra                         Neha   Mishra   
12                tanvi sharma                          Tanvi Sharma   
13         kanci        nagori                   Kanci        Nagori   
14                harshit shah                          Harshit Shah   
15                 mehul mehta                           Mehul Mehta   
16                  bhumi shah                            Bhumi Shah   
17               riya sanghavi                         Riya Sanghavi   
18                manish desai                          Manish Desai   
19             hitendra   khan                       Hitendra   Khan   
20               bharat kapoor                         Bharat Kapoor   
21                 dipesh shah                           Dipesh Shah   
22               kanan somaiya                         Kanan Somaiya   
23                karan kapoor                          Karan Kapoor   
24                  tina mehta                            Tina Mehta   
25                krystal shah                          Krystal Shah   
26                  kirit khan                            Kirit Khan   
27                kushal desai                          Kushal Desai   

                  Unnamed: 4          Unnamed: 5  
0   Removes all extra spaces  The Perfect Answer  
1                       TRIM       PROPER + TRIM  
2                 raHul sH

Use the r' string in windows when using the full relative path of a file from a different directory [Unicode issue]

#### How to deal with column names and row numbers??

1. In Pandas, the first row is always considered a coloumn name! otherwise, give header = None
2. Row indexes are also created by Pandas by default (auto-populated) which starts from zero.
3. Pandas are used only incase of STRUCTURED data! 
4. Limitation: Cannot be used when data is UNstructured.
5. Datatype of the entire table which Pandas create ----> DATAFRAME (tabular structure)


In [6]:
df = pd.read_excel(r"C:\Users\santa\Downloads\Excel Formulas Masterclass - Students (1).xlsx")

In [7]:
type(df)                                                              # datatype: DATAFRAME!         

pandas.core.frame.DataFrame

What to do when the file doesnot have a column name?

In [9]:
pd.read_excel('airline1.xls',header=None)

0       1      2       3      4      5
0   YEAR       Y      W       R      L      K
1   1948   1.214  0.243  0.1454  1.415  0.612
2   1949   1.354   0.26  0.2181  1.384  0.559
3   1950   1.569  0.278  0.3157  1.388  0.573
4   1951   1.948  0.297   0.394   1.55  0.564
5   1952   2.265   0.31  0.3559  1.802  0.574
6   1953   2.731  0.322  0.3593  1.926  0.711
7   1954   3.025  0.335  0.4025  1.964  0.776
8   1955   3.562   0.35  0.3961  2.116  0.827
9   1956   3.979  0.361  0.3822  2.435    0.8
10  1957    4.42  0.379  0.3045  2.707  0.921
11  1958   4.563  0.391  0.3284  2.706  1.067
12  1959   5.385  0.426  0.3856  2.846  1.083
13  1960   5.554  0.441  0.3193  3.089  1.481
14  1961   5.465   0.46  0.3079  3.122  1.736
15  1962   5.825  0.485  0.3783  3.184  1.926
16  1963   6.876  0.506   0.418  3.263  2.041
17  1964   7.823  0.538  0.5163  3.412  1.997
18  1965    9.12  0.564  0.5879  3.623  2.257
19  1966  10.512  0.586  0.5369  4.074  2.742
20  1967   13.02  0.622  0.4443   4.71  3.564
21  1968  15.261  0.666  0.3052  5.217  4.767
22  1969  16.313  0.731  0.2332  5.569  6.511
23  1970  16.002  0.831  0.1883  5.495  7.627
24  1971  15.876  0.906  0.2023  5.334  8.673
25  1972  16.662      1  0.2506  5.345  8.331
26  1973  17.014  1.056  0.2668  5.662  8.557
27  1974  19.305  1.131  0.2664  5.729  9.508
28  1975  18.721  1.247  0.2301  5.722  9.062
29  1976   19.25  1.375  0.3452  5.762  8.262
30  1977  20.647  1.544  0.4508  5.877  7.474
31  1978  22.726  1.703  0.5877  6.108  7.104
32  1979  23.619  1.779  0.5346  6.852  6.874

It gives a column name and row name by default but now the first record in the dataset is not considered as a header by pandas, as header = None

Q: Can we use custom column names? Pass the exact number of names required sequentially in a List! names =[ ]

In [10]:
pd.read_excel('airline1.xls',names = ['a','b','c','d','e','f'])   

a       b      c       d      e      f
0   1948   1.214  0.243  0.1454  1.415  0.612
1   1949   1.354  0.260  0.2181  1.384  0.559
2   1950   1.569  0.278  0.3157  1.388  0.573
3   1951   1.948  0.297  0.3940  1.550  0.564
4   1952   2.265  0.310  0.3559  1.802  0.574
5   1953   2.731  0.322  0.3593  1.926  0.711
6   1954   3.025  0.335  0.4025  1.964  0.776
7   1955   3.562  0.350  0.3961  2.116  0.827
8   1956   3.979  0.361  0.3822  2.435  0.800
9   1957   4.420  0.379  0.3045  2.707  0.921
10  1958   4.563  0.391  0.3284  2.706  1.067
11  1959   5.385  0.426  0.3856  2.846  1.083
12  1960   5.554  0.441  0.3193  3.089  1.481
13  1961   5.465  0.460  0.3079  3.122  1.736
14  1962   5.825  0.485  0.3783  3.184  1.926
15  1963   6.876  0.506  0.4180  3.263  2.041
16  1964   7.823  0.538  0.5163  3.412  1.997
17  1965   9.120  0.564  0.5879  3.623  2.257
18  1966  10.512  0.586  0.5369  4.074  2.742
19  1967  13.020  0.622  0.4443  4.710  3.564
20  1968  15.261  0.666  0.3052  5.217  4.767
21  1969  16.313  0.731  0.2332  5.569  6.511
22  1970  16.002  0.831  0.1883  5.495  7.627
23  1971  15.876  0.906  0.2023  5.334  8.673
24  1972  16.662  1.000  0.2506  5.345  8.331
25  1973  17.014  1.056  0.2668  5.662  8.557
26  1974  19.305  1.131  0.2664  5.729  9.508
27  1975  18.721  1.247  0.2301  5.722  9.062
28  1976  19.250  1.375  0.3452  5.762  8.262
29  1977  20.647  1.544  0.4508  5.877  7.474
30  1978  22.726  1.703  0.5877  6.108  7.104
31  1979  23.619  1.779  0.5346  6.852  6.874

if a file is @ or any other character separated rather than csv(comma separated value) file,

separator ---> sep = '@'... for csv, delimiter/separator(sep) =','

#### skiprows=[  ]

In [13]:
pd.read_excel('airline1.xls',names = ['a','b','c','d','e','f'],skiprows=[2,4,6,8,10])   

a       b      c       d      e      f
0   1948   1.214  0.243  0.1454  1.415  0.612
1   1950   1.569  0.278  0.3157  1.388  0.573
2   1952   2.265  0.310  0.3559  1.802  0.574
3   1954   3.025  0.335  0.4025  1.964  0.776
4   1956   3.979  0.361  0.3822  2.435  0.800
5   1958   4.563  0.391  0.3284  2.706  1.067
6   1959   5.385  0.426  0.3856  2.846  1.083
7   1960   5.554  0.441  0.3193  3.089  1.481
8   1961   5.465  0.460  0.3079  3.122  1.736
9   1962   5.825  0.485  0.3783  3.184  1.926
10  1963   6.876  0.506  0.4180  3.263  2.041
11  1964   7.823  0.538  0.5163  3.412  1.997
12  1965   9.120  0.564  0.5879  3.623  2.257
13  1966  10.512  0.586  0.5369  4.074  2.742
14  1967  13.020  0.622  0.4443  4.710  3.564
15  1968  15.261  0.666  0.3052  5.217  4.767
16  1969  16.313  0.731  0.2332  5.569  6.511
17  1970  16.002  0.831  0.1883  5.495  7.627
18  1971  15.876  0.906  0.2023  5.334  8.673
19  1972  16.662  1.000  0.2506  5.345  8.331
20  1973  17.014  1.056  0.2668  5.662  8.557
21  1974  19.305  1.131  0.2664  5.729  9.508
22  1975  18.721  1.247  0.2301  5.722  9.062
23  1976  19.250  1.375  0.3452  5.762  8.262
24  1977  20.647  1.544  0.4508  5.877  7.474
25  1978  22.726  1.703  0.5877  6.108  7.104
26  1979  23.619  1.779  0.5346  6.852  6.874

Check with the last table, data missing from row numbers 2,4,6..

## STUDY: In-built functions in Pandas

In [15]:
df = pd.read_csv("mohit2.csv")

In [18]:
type(df)                                         # DataFrame ---> tabular data

pandas.core.frame.DataFrame

1. What are the different data types in the columns of the file?  .dtypes

In [16]:
df.dtypes                                        # dtypes ---> data types of columns

Ticket ID                         int64
Subject                          object
Status                           object
Priority                         object
Source                           object
Type                             object
Agent                            object
Group                            object
Created time                     object
Due by Time                      object
Resolved time                    object
Closed time                      object
Last update time                 object
Initial response time            object
Time tracked                     object
First response time (in hrs)     object
Resolution time (in hrs)         object
Agent interactions                int64
Customer interactions            object
Resolution status                object
First response status            object
Tags                             object
Survey results                  float64
Association type                 object
Internal agent                   object


In [19]:
df.head(3)            #  Top 3....... by default head shows top 5 ------>    .head()

Ticket ID                                           Subject  Status  \
0     132792                  Demotion of BDM's- Team Subhendu  Closed   
1     177692                     Mapping of BDA || TNL21864505  Closed   
2     177828  MAPPING OF ABHIMANYU SINGH BAGHEL ( TNL21855561)  Closed   

  Priority Source Type           Agent                        Group  \
0      Low  Email  NaN  mohit chandak1  Achieve, DB & LS Management   
1      Low  Email  NaN  mohit chandak1                     No Group   
2      Low  Email  NaN  mohit chandak1                     No Group   

       Created time       Due by Time  ... Every response status     Product  \
0  07-10-2021 14:01  08-10-2021 14:01  ...                   NaN  No Product   
1  25-11-2021 13:00  24-12-2021 10:43  ...                   NaN  No Product   
2  25-11-2021 13:54  26-11-2021 14:03  ...                   NaN  No Product   

  FD Agent Name Coordination Team Agents AT Agents Note Assignment Mode  \
0           NaN                      NaN       NaN  NaN             NaN   
1           NaN                      NaN       NaN  NaN             NaN   
2           NaN                      NaN       NaN  NaN             NaN   

   Ticket Closure Mode         Full name                  Contact ID  
0                  NaN  Subhendu Chandra  subhendu.chandra@byjus.com  
1                  NaN     Subham Sharma     subham.sharma@byjus.com  
2                  NaN  Simranjeet Singh  simranjeet.singh@byjus.com  

[3 rows x 36 columns]

In [24]:
df.tail(2)                 # last 3, by default shows bottom 5  ------>     .tail()

Ticket ID                      Subject    Status Priority Source Type  \
6849     671332               MAPPING CHANGE  Resolved      Low  Email  NaN   
6850     671636  Re: CHANGE IN LEAD LANGUAGE  Resolved      Low  Email  NaN   

               Agent                                      Group  \
6849  mohit chandak1                               Source Group   
6850  mohit chandak1  Individual Leads creations & reallocation   

          Created time       Due by Time  ... Every response status  \
6849  04-01-2023 13:59  05-01-2023 13:59  ...                   NaN   
6850  04-01-2023 20:59  05-01-2023 20:59  ...                   NaN   

         Product FD Agent Name Coordination Team Agents AT Agents Note  \
6849  No Product           NaN                      NaN       NaN  NaN   
6850  No Product           NaN                      NaN       NaN  NaN   

     Assignment Mode  Ticket Closure Mode         Full name  \
6849             NaN                  NaN   Souptik Kushary   
6850             NaN                  NaN  Debashish Baidya   

                      Contact ID  
6849   souptik.kushary@byjus.com  
6850  debashish.baidya@byjus.com  

[2 rows x 36 columns]

The console cannot show the entire table but she loads it all! 

In [26]:
# what are the column names available? Output comes in a [list]

df.columns


Index(['Ticket ID', 'Subject', 'Status', 'Priority', 'Source', 'Type', 'Agent',
       'Group', 'Created time', 'Due by Time', 'Resolved time', 'Closed time',
       'Last update time', 'Initial response time', 'Time tracked',
       'First response time (in hrs)', 'Resolution time (in hrs)',
       'Agent interactions', 'Customer interactions', 'Resolution status',
       'First response status', 'Tags', 'Survey results', 'Association type',
       'Internal agent', 'Internal group', 'Every response status', 'Product',
       'FD Agent Name', 'Coordination Team Agents', 'AT Agents', 'Note',
       'Assignment Mode', 'Ticket Closure Mode', 'Full name', 'Contact ID'],
      dtype='object')

In [30]:
# Find data from some of the columns...not all of the table...  [FOR SINGLE COLUMN]

df["Agent"]



0       mohit chandak1
1       mohit chandak1
2       mohit chandak1
3       mohit chandak1
4       mohit chandak1
             ...      
6846    mohit chandak1
6847    mohit chandak1
6848    mohit chandak1
6849    mohit chandak1
6850    mohit chandak1
Name: Agent, Length: 6851, dtype: object

In [31]:
a=df["Agent"]

type(a)                                 # datatype : Series


pandas.core.series.Series

As we are pulling out only 1 single column "Agent"---> Datatype = Series

#### There are 2 types of Data-types in Pandas library.
1. Series: for single column/ single row          ........  [list]
2. DataFrame: for complete tabular structure      ........ DataFrames are basically combination of multiple Series

Series: It is similar to a list! Heterogenous datatypes,indexed/ordered. Pandas library recognizes it as a series when a single row / column is being operated on. This single row/column (series) is like a single List.

DataFrame: Combination of multiple columns(singular: Series) vertically or multiple rows(singular: Series) horizontally. They provide for the complete tabular structure.

In [33]:
# Find data from some of the columns...not all of the table...  [FOR MULTIPLE COLUMN]

df.columns


Index(['Ticket ID', 'Subject', 'Status', 'Priority', 'Source', 'Type', 'Agent',
       'Group', 'Created time', 'Due by Time', 'Resolved time', 'Closed time',
       'Last update time', 'Initial response time', 'Time tracked',
       'First response time (in hrs)', 'Resolution time (in hrs)',
       'Agent interactions', 'Customer interactions', 'Resolution status',
       'First response status', 'Tags', 'Survey results', 'Association type',
       'Internal agent', 'Internal group', 'Every response status', 'Product',
       'FD Agent Name', 'Coordination Team Agents', 'AT Agents', 'Note',
       'Assignment Mode', 'Ticket Closure Mode', 'Full name', 'Contact ID'],
      dtype='object')

In [34]:
# Use an extra [] bracket to put it as a list within a list... 

#    df['','']---> df[['','']]  ...Send a [list of columns] inside the [] brackets for df calling...


df[['Subject','Priority']]


Subject Priority
0                      Demotion of BDM's- Team Subhendu      Low
1                         Mapping of BDA || TNL21864505      Low
2      MAPPING OF ABHIMANYU SINGH BAGHEL ( TNL21855561)      Low
3     Provisional K3 Manager Activation 02nd-Dec-202...      Low
4                                       LS A/c creation      Low
...                                                 ...      ...
6846                           CHANGES IN SALES PROCESS      Low
6847                                  LS Not responding      Low
6848                                     LS NOT WORKING      Low
6849                                     MAPPING CHANGE      Low
6850                        Re: CHANGE IN LEAD LANGUAGE      Low

[6851 rows x 2 columns]

Put the columns in a list and then send the whole [list] into the [ ] outer brackets of calling function

In [35]:
# Storing this table in a variable and checking the datatype....

df1 = df[['Subject','Priority']]             # ... combination of Series

type(df1)


pandas.core.frame.DataFrame

DataFrame gives the tabular structure to the data when number of columns/rows increases from one!

In [36]:
# Anomaly:

type(df[['Agent']])          # passing a single column as a list within a list



pandas.core.frame.DataFrame

Here, the datatype is DataFrame as the inputs were passed in a list, within a list [ ]

In [37]:
ls


 Volume in drive C is OS
 Volume Serial Number is 1600-9EB4

 Directory of C:\Users\santa

15-03-2023  13:02    <DIR>          .
22-09-2022  14:03    <DIR>          ..
22-08-2022  12:19    <DIR>          .anaconda
08-02-2023  16:31    <DIR>          .conda
22-08-2022  12:19                25 .condarc
22-08-2022  12:18    <DIR>          .continuum
07-03-2023  12:25                58 .gitconfig
20-02-2023  11:11                53 .git-for-windows-updater
10-07-2022  18:25    <DIR>          .idlerc
14-03-2023  11:35    <DIR>          .ipynb_checkpoints
22-08-2022  13:10    <DIR>          .ipython
22-08-2022  14:04    <DIR>          .jupyter
14-03-2023  12:17    <DIR>          .matplotlib
27-08-2022  08:26                43 .python_history
27-02-2023  14:06               527 .vivaldi_reporting_data
04-01-2023  10:28    <DIR>          .vscode
17-02-2023  14:53    <DIR>          __pycache__
14-03-2023  12:07             1,173 addresses.csv
14-03-2023  12:55            32,256 airline1.xls
18-

In [38]:
pd.read_excel('basketball.xlsx')   

Unnamed: 0   Rk          Player Pos Age   Tm   G  GS    MP   FG  ...  \
0             0    1      Quincy Acy  PF  24  NYK  68  22  1287  152  ...   
1             1    2    Jordan Adams  SG  20  MEM  30   0   248   35  ...   
2             2    3    Steven Adams   C  21  OKC  70  67  1771  217  ...   
3             3    4     Jeff Adrien  PF  28  MIN  17   0   215   19  ...   
4             4    5   Arron Afflalo  SG  29  TOT  78  72  2502  375  ...   
..          ...  ...             ...  ..  ..  ...  ..  ..   ...  ...  ...   
670         670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  ...   
671         671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  ...   
672         672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  ...   
673         673  491     Cody Zeller   C  22  CHO  62  45  1487  172  ...   
674         674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  ...   

      FT%  ORB  DRB  TRB  AST  STL BLK  TOV   PF   PTS  
0    .784   79  222  301   68   27  22   60  147   398  
1    .609    9   19   28   16   16   7   14   24    94  
2    .502  199  324  523   66   38  86   99  222   537  
3    .579   23   54   77   15    4   9    9   30    60  
4    .843   27  220  247  129   41   7  116  167  1035  
..    ...  ...  ...  ...  ...  ...  ..  ...  ...   ...  
670  .655  127  284  411  173  124  25  117  171  1071  
671  .682   75  170  245  135   86  17   75  115   685  
672  .606   52  114  166   38   38   8   42   56   386  
673  .774   97  265  362  100   34  49   62  156   472  
674  .823  146  319  465  113   18  52   76  205   833  

[675 rows x 31 columns]

Press shift + tab after , to see diff parameters like sheet_name= 'sheetname' to read different sheets in a excel file

How to get the name of the sheets?


In [39]:
df = pd.ExcelFile('basketball.xlsx')         # use pandas function ---> pd.ExcelFile('file_name.xlsx')

df.sheet_names                               # .sheet_names ---> to find the name of the sheets

['Sheet1']

This file has only 1 sheet!

If it had multiple sheets and we needed to auomate the reading of all the sheets in an excel file:

In [40]:
for i in df.sheet_names:
    pd.read_excel('basketball.xlsx',sheet_name=i)

### DATA FROM GITHUB:

In [41]:
pd.read_csv("https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv")

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

TITANIC data Raw pulled directly from github using raw url

### Working with Pandas [RECORDED]

In [42]:
ls


 Volume in drive C is OS
 Volume Serial Number is 1600-9EB4

 Directory of C:\Users\santa

15-03-2023  15:18    <DIR>          .
22-09-2022  14:03    <DIR>          ..
22-08-2022  12:19    <DIR>          .anaconda
08-02-2023  16:31    <DIR>          .conda
22-08-2022  12:19                25 .condarc
22-08-2022  12:18    <DIR>          .continuum
07-03-2023  12:25                58 .gitconfig
20-02-2023  11:11                53 .git-for-windows-updater
10-07-2022  18:25    <DIR>          .idlerc
15-03-2023  15:10    <DIR>          .ipynb_checkpoints
22-08-2022  13:10    <DIR>          .ipython
22-08-2022  14:04    <DIR>          .jupyter
14-03-2023  12:17    <DIR>          .matplotlib
27-08-2022  08:26                43 .python_history
27-02-2023  14:06               527 .vivaldi_reporting_data
04-01-2023  10:28    <DIR>          .vscode
17-02-2023  14:53    <DIR>          __pycache__
14-03-2023  12:07             1,173 addresses.csv
14-03-2023  12:55            32,256 airline1.xls
18-

Extracting epl data from fbref: as on 13/3/2023

In [47]:
df = pd.read_html("https://fbref.com/en/comps/9/Premier-League-Stats.html")

.read_html : always tries to scrap tabular form of data, html tier or table tag

In [51]:
type(df)

list

.read_html returns a list of DataFrames or tables present in the html page

In [52]:
len(df)         # There is data in 24 indexes in the list

24

There are 24 tables/DataFrames in the html page which can be accessed individually using list indexing

In [53]:
df[0]         # Using indexing to access the different tables in different index posiion...

Rk            Squad  MP   W   D   L  GF  GA  GD  Pts  Pts/MP    xG   xGA  \
0    1          Arsenal  27  21   3   3  62  25  37   66    2.44  52.2  26.3   
1    2  Manchester City  27  19   4   4  67  25  42   61    2.26  56.1  21.5   
2    3   Manchester Utd  26  15   5   6  41  35   6   50    1.92  40.8  32.6   
3    4        Tottenham  27  15   3   9  49  37  12   48    1.78  38.7  31.4   
4    5    Newcastle Utd  25  11  11   3  37  18  19   44    1.76  39.3  24.5   
5    6        Liverpool  26  12   6   8  47  29  18   42    1.62  47.5  34.7   
6    7         Brighton  24  11   6   7  45  31  14   39    1.63  42.2  27.7   
7    8           Fulham  27  11   6  10  38  37   1   39    1.44  33.7  44.9   
8    9        Brentford  25   9  11   5  40  33   7   38    1.52  36.6  31.4   
9   10          Chelsea  26  10   7   9  27  26   1   37    1.42  31.3  33.1   
10  11      Aston Villa  26  10   5  11  32  39  -7   35    1.35  31.7  39.5   
11  12   Crystal Palace  26   6   9  11  21  33 -12   27    1.04  22.9  37.2   
12  13           Wolves  27   7   6  14  20  37 -17   27    1.00  26.2  38.9   
13  14  Nott'ham Forest  26   6   8  12  21  47 -26   26    1.00  27.8  41.6   
14  15          Everton  27   6   7  14  20  38 -18   25    0.93  29.4  44.6   
15  16   Leicester City  26   7   3  16  37  46  -9   24    0.92  32.9  43.1   
16  17         West Ham  26   6   6  14  24  34 -10   24    0.92  33.5  31.4   
17  18      Bournemouth  26   6   6  14  25  51 -26   24    0.92  22.1  44.1   
18  19     Leeds United  26   5   8  13  31  42 -11   23    0.88  32.4  39.2   
19  20      Southampton  26   6   4  16  20  41 -21   22    0.85  24.9  34.3   

     xGD  xGD/90     Last 5  Attendance  \
0   26.0    0.96  W W W W W       60196   
1   34.6    1.28  W D W W W       53219   
2    8.2    0.31  D W W L D       73749   
3    7.3    0.27  L W W L W       61654   
4   14.8    0.59  D D L L W       52241   
5   12.7    0.49  W D W W L       53197   
6   14.4    0.60  W D L W D       31501   
7  -11.3   -0.42  W W D L L       23502   
8    5.3    0.21  W D D W L       17076   
9   -1.8   -0.07  D L L W W       39969   
10  -7.8   -0.30  L L W W D       41681   
11 -14.3   -0.55  D D D L L       24882   
12 -12.7   -0.47  L D L W L       31584   
13 -13.8   -0.53  L D L D L       29148   
14 -15.2   -0.56  W L L D W       39233   
15 -10.1   -0.39  W L L L L       31772   
16   2.1    0.08  D L W L D       62454   
17 -22.0   -0.85  D W L L W       10371   
18  -6.8   -0.26  L L W L D       36496   
19  -9.5   -0.36  L W L W D       30498   

                              Top Team Scorer         Goalkeeper  Notes  
0                             Martinelli - 12     Aaron Ramsdale    NaN  
1                         Erling Haaland - 28            Ederson    NaN  
2                        Marcus Rashford - 14       David de Gea    NaN  
3                             Harry Kane - 20        Hugo Lloris    NaN  
4                         Miguel Almirón - 11          Nick Pope    NaN  
5                          Mohamed Salah - 11            Alisson    NaN  
6   Leandro Trossard, Alexis Mac Allister - 7     Robert Sánchez    NaN  
7                    Aleksandar Mitrović - 11         Bernd Leno    NaN  
8                             Ivan Toney - 15         David Raya    NaN  
9                             Kai Havertz - 6  Kepa Arrizabalaga    NaN  
10                          Ollie Watkins - 9  Emiliano Martínez    NaN  
11                          Wilfried Zaha - 6     Vicente Guaita    NaN  
12            Rúben Neves, Daniel Podence - 5            José Sá    NaN  
13                        Brennan Johnson - 7     Dean Henderson    NaN  
14                           Demarai Gray - 4    Jordan Pickford    NaN  
15                         James Maddison - 9         Danny Ward    NaN  
16            Jarrod Bowen, Saïd Benrahma - 4   Łukasz Fabiański    NaN  
17                         Philip Billing - 6               Neto    NaN  
18           

In [54]:
df[1]

Unnamed: 0_level_0 Unnamed: 1_level_0 Home                            ...  \
                   Rk              Squad   MP   W  D  L  GF  GA  GD Pts  ...   
0                   1            Arsenal   13  10  2  1  34  16  18  32  ...   
1                   2    Manchester City   13  11  1  1  43  13  30  34  ...   
2                   3     Manchester Utd   13   9  3  1  24   8  16  30  ...   
3                   4          Tottenham   14  10  0  4  29  16  13  30  ...   
4                   5      Newcastle Utd   13   7  5  1  21   9  12  26  ...   
5                   6          Liverpool   13   9  3  1  34   9  25  30  ...   
6                   7           Brighton   12   6  2  4  21  11  10  20  ...   
7                   8             Fulham   14   6  4  4  21  20   1  22  ...   
8                   9          Brentford   13   7  5  1  27  13  14  26  ...   
9                  10            Chelsea   12   6  3  3  14   8   6  21  ...   
10                 11        Aston Villa   13   6  2  5  20  19   1  20  ...   
11                 12     Crystal Palace   14   4  5  5  12  18  -6  17  ...   
12                 13             Wolves   13   5  2  6  10  15  -5  17  ...   
13                 14    Nott'ham Forest   13   5  5  3  17  15   2  20  ...   
14                 15            Everton   14   5  2  7  12  16  -4  17  ...   
15                 16     Leicester City   13   3  3  7  16  17  -1  12  ...   
16                 17           West Ham   13   5  3  5  17  14   3  18  ...   
17                 18        Bournemouth   13   4  4  5  13  16  -3  16  ...   
18                 19       Leeds United   13   4  5  4  18  18   0  17  ...   
19                 20        Southampton   12   2  3  7  11  19  -8   9  ...   

   Away                                                  
      L  GF  GA  GD Pts Pts/MP    xG   xGA   xGD xGD/90  
0     2  28   9  19  34   2.43  22.7  12.8   9.9   0.71  
1     3  24  12  12  27   1.93  26.4  13.7  12.7   0.91  
2     5  17  27 -10  20   1.54  16.9  19.5  -2.7  -0.21  
3     5  20  21  -1  18   1.38  15.6  17.3  -1.6  -0.13  
4     2  16   9   7  18   1.50  14.7  13.0   1.7   0.14  
5     7  13  20  -7  12   0.92  20.5  21.2  -0.6  -0.05  
6     3  24  20   4  19   1.58  19.6  14.7   4.9   0.41  
7     6  17  17   0  17   1.31  15.1  23.9  -8.8  -0.68  
8     4  13  20  -7  12   1.00  15.6  16.0  -0.4  -0.04  
9     6  13  18  -5  16   1.14  15.7  19.0  -3.2  -0.23  
10    6  12  20  -8  15   1.15  14.0  20.8  -6.7  -0.52  
11    6   9  15  -6  10   0.83  10.5  17.1  -6.6  -0.55  
12    8  10  22 -12  10   0.71  12.8  20.4  -7.6  -0.54  
13    9   4  32 -28   6   0.46  11.7  23.6 -11.9  -0.91  
14    7   8  22 -14   8   0.62  11.8  24.7 -12.9  -0.99  
15    9  21  29  -8  12   0.92  20.2  27.2  -6.9  -0.53  
16    9   7  20 -13   6   0.46  14.5  17.1  -2.5  -0.19  
17    9  12  35 -23   8   0.62  10.1  26.0 -15.9  -1.22  
18    9  13  24 -11   6   0.46  16.3  19.6  -3.3  -0.25  
19    9   9  22 -13  13   0.93  11.1  18.8  -7.7  -0.55  

[20 rows x 28 columns]

In [56]:
type(df[0])

pandas.core.frame.DataFrame

In [57]:
df1 = df[0]      # saving the first table in a separate variable...

In [58]:
df1.columns      # column headers in the table...

Index(['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP',
       'xG', 'xGA', 'xGD', 'xGD/90', 'Last 5', 'Attendance', 'Top Team Scorer',
       'Goalkeeper', 'Notes'],
      dtype='object')

In [60]:
df1.dtypes                          # datatypes of column headers

Rk                   int64
Squad               object
MP                   int64
W                    int64
D                    int64
L                    int64
GF                   int64
GA                   int64
GD                   int64
Pts                  int64
Pts/MP             float64
xG                 float64
xGA                float64
xGD                float64
xGD/90             float64
Last 5              object
Attendance           int64
Top Team Scorer     object
Goalkeeper          object
Notes              float64
dtype: object

In [62]:
df1[['Squad','MP','W','L']]

Squad  MP   W   L
0           Arsenal  27  21   3
1   Manchester City  27  19   4
2    Manchester Utd  26  15   6
3         Tottenham  27  15   9
4     Newcastle Utd  25  11   3
5         Liverpool  26  12   8
6          Brighton  24  11   7
7            Fulham  27  11  10
8         Brentford  25   9   5
9           Chelsea  26  10   9
10      Aston Villa  26  10  11
11   Crystal Palace  26   6  11
12           Wolves  27   7  14
13  Nott'ham Forest  26   6  12
14          Everton  27   6  14
15   Leicester City  26   7  16
16         West Ham  26   6  14
17      Bournemouth  26   6  14
18     Leeds United  26   5  13
19      Southampton  26   6  16

### How to save a DataFrame into a .csv file?

In [73]:
df1.to_csv('epl.csv',index=False)                                                # save

In [74]:
pd.read_csv('epl.csv')                                             # reading from the saved new file

Rk            Squad  MP   W   D   L  GF  GA  GD  Pts  Pts/MP    xG   xGA  \
0    1          Arsenal  27  21   3   3  62  25  37   66    2.44  52.2  26.3   
1    2  Manchester City  27  19   4   4  67  25  42   61    2.26  56.1  21.5   
2    3   Manchester Utd  26  15   5   6  41  35   6   50    1.92  40.8  32.6   
3    4        Tottenham  27  15   3   9  49  37  12   48    1.78  38.7  31.4   
4    5    Newcastle Utd  25  11  11   3  37  18  19   44    1.76  39.3  24.5   
5    6        Liverpool  26  12   6   8  47  29  18   42    1.62  47.5  34.7   
6    7         Brighton  24  11   6   7  45  31  14   39    1.63  42.2  27.7   
7    8           Fulham  27  11   6  10  38  37   1   39    1.44  33.7  44.9   
8    9        Brentford  25   9  11   5  40  33   7   38    1.52  36.6  31.4   
9   10          Chelsea  26  10   7   9  27  26   1   37    1.42  31.3  33.1   
10  11      Aston Villa  26  10   5  11  32  39  -7   35    1.35  31.7  39.5   
11  12   Crystal Palace  26   6   9  11  21  33 -12   27    1.04  22.9  37.2   
12  13           Wolves  27   7   6  14  20  37 -17   27    1.00  26.2  38.9   
13  14  Nott'ham Forest  26   6   8  12  21  47 -26   26    1.00  27.8  41.6   
14  15          Everton  27   6   7  14  20  38 -18   25    0.93  29.4  44.6   
15  16   Leicester City  26   7   3  16  37  46  -9   24    0.92  32.9  43.1   
16  17         West Ham  26   6   6  14  24  34 -10   24    0.92  33.5  31.4   
17  18      Bournemouth  26   6   6  14  25  51 -26   24    0.92  22.1  44.1   
18  19     Leeds United  26   5   8  13  31  42 -11   23    0.88  32.4  39.2   
19  20      Southampton  26   6   4  16  20  41 -21   22    0.85  24.9  34.3   

     xGD  xGD/90     Last 5  Attendance  \
0   26.0    0.96  W W W W W       60196   
1   34.6    1.28  W D W W W       53219   
2    8.2    0.31  D W W L D       73749   
3    7.3    0.27  L W W L W       61654   
4   14.8    0.59  D D L L W       52241   
5   12.7    0.49  W D W W L       53197   
6   14.4    0.60  W D L W D       31501   
7  -11.3   -0.42  W W D L L       23502   
8    5.3    0.21  W D D W L       17076   
9   -1.8   -0.07  D L L W W       39969   
10  -7.8   -0.30  L L W W D       41681   
11 -14.3   -0.55  D D D L L       24882   
12 -12.7   -0.47  L D L W L       31584   
13 -13.8   -0.53  L D L D L       29148   
14 -15.2   -0.56  W L L D W       39233   
15 -10.1   -0.39  W L L L L       31772   
16   2.1    0.08  D L W L D       62454   
17 -22.0   -0.85  D W L L W       10371   
18  -6.8   -0.26  L L W L D       36496   
19  -9.5   -0.36  L W L W D       30498   

                              Top Team Scorer         Goalkeeper  Notes  
0                             Martinelli - 12     Aaron Ramsdale    NaN  
1                         Erling Haaland - 28            Ederson    NaN  
2                        Marcus Rashford - 14       David de Gea    NaN  
3                             Harry Kane - 20        Hugo Lloris    NaN  
4                         Miguel Almirón - 11          Nick Pope    NaN  
5                          Mohamed Salah - 11            Alisson    NaN  
6   Leandro Trossard, Alexis Mac Allister - 7     Robert Sánchez    NaN  
7                    Aleksandar Mitrović - 11         Bernd Leno    NaN  
8                             Ivan Toney - 15         David Raya    NaN  
9                             Kai Havertz - 6  Kepa Arrizabalaga    NaN  
10                          Ollie Watkins - 9  Emiliano Martínez    NaN  
11                          Wilfried Zaha - 6     Vicente Guaita    NaN  
12            Rúben Neves, Daniel Podence - 5            José Sá    NaN  
13                        Brennan Johnson - 7     Dean Henderson    NaN  
14                           Demarai Gray - 4    Jordan Pickford    NaN  
15                         James Maddison - 9         Danny Ward    NaN  
16            Jarrod Bowen, Saïd Benrahma - 4   Łukasz Fabiański    NaN  
17                         Philip Billing - 6               Neto    NaN  
18           

How to remove the row indexes which are not part of the actual data? ,index=False. Check the csv file in local... the extra row indexes are gone!

### Dictionary Format of Data: JSON

In [85]:
d = """{"name":"sudhanshu",
"email_id":"sudh@inueron.ai",
"tech":["ML","DL","CV"],
"platform":["techneuron","kidsneuron","inueron"]}
"""

In [83]:
type(d)

str

Convert this data into a tabular format or DataFrame?!

In [76]:
pd.DataFrame(d)

ValueError: DataFrame constructor not properly called!

In [78]:
import json         # JavaScript Object Notation format

In [86]:
result = json.loads(d)

In [87]:
type(result)

dict

In [89]:
pd.DataFrame(result)

name         email_id tech    platform
0  sudhanshu  sudh@inueron.ai   ML  techneuron
1  sudhanshu  sudh@inueron.ai   DL  kidsneuron
2  sudhanshu  sudh@inueron.ai   CV     inueron

No. of elementsin the list must be the same to parse the json into DataFrame as the keys are taken as column headers and the moderate number of elements in one of the keys is taken  as the number of rows where data needs to be filled. There are 3 rows of data as the list in one of the values contains 3 elements.

In [91]:
pd.DataFrame(result['tech'])   # list can be converted into DataFrame

0
0  ML
1  DL
2  CV

Check the max number of elements in the list which actually forms number of columns for the DataFrame

#### READ JSON FROM URL [DATA LOAD]

url = https://api.github.com/repos/pandas-dev/pandas/issues
<===============    link to get the data for dummy json file 

In [92]:
pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com/repos/pandas-dev/pandas...   
3   https://api.github.com/repos/pandas-dev/pandas...   
4   https://api.github.com/repos/pandas-dev/pandas...   
5   https://api.github.com/repos/pandas-dev/pandas...   
6   https://api.github.com/repos/pandas-dev/pandas...   
7   https://api.github.com/repos/pandas-dev/pandas...   
8   https://api.github.com/repos/pandas-dev/pandas...   
9   https://api.github.com/repos/pandas-dev/pandas...   
10  https://api.github.com/repos/pandas-dev/pandas...   
11  https://api.github.com/repos/pandas-dev/pandas...   
12  https://api.github.com/repos/pandas-dev/pandas...   
13  https://api.github.com/repos/pandas-dev/pandas...   
14  https://api.github.com/repos/pandas-dev/pandas...   
15  https://api.github.com/repos/pandas-dev/pandas...   
16  https://api.github.com/repos/pandas-dev/pandas...   
17  https://api.github.com/repos/pandas-dev/pandas...   
18  https://api.github.com/repos/pandas-dev/pandas...   
19  https://api.github.com/repos/pandas-dev/pandas...   
20  https://api.github.com/repos/pandas-dev/pandas...   
21  https://api.github.com/repos/pandas-dev/pandas...   
22  https://api.github.com/repos/pandas-dev/pandas...   
23  https://api.github.com/repos/pandas-dev/pandas...   
24  https://api.github.com/repos/pandas-dev/pandas...   
25  https://api.github.com/repos/pandas-dev/pandas...   
26  https://api.github.com/repos/pandas-dev/pandas...   
27  https://api.github.com/repos/pandas-dev/pandas...   
28  https://api.github.com/repos/pandas-dev/pandas...   
29  https://api.github.com/repos/pandas-dev/pandas...   

                                    repository_url  \
0   https://api.github.com/repos/pandas-dev/pandas   
1   https://api.github.com/repos/pandas-dev/pandas   
2   https://api.github.com/repos/pandas-dev/pandas   
3   https://api.github.com/repos/pandas-dev/pandas   
4   https://api.github.com/repos/pandas-dev/pandas   
5   https://api.github.com/repos/pandas-dev/pandas   
6   https://api.github.com/repos/pandas-dev/pandas   
7   https://api.github.com/repos/pandas-dev/pandas   
8   https://api.github.com/repos/pandas-dev/pandas   
9   https://api.github.com/repos/pandas-dev/pandas   
10  https://api.github.com/repos/pandas-dev/pandas   
11  https://api.github.com/repos/pandas-dev/pandas   
12  https://api.github.com/repos/pandas-dev/pandas   
13  https://api.github.com/repos/pandas-dev/pandas   
14  https://api.github.com/repos/pandas-dev/pandas   
15  https://api.github.com/repos/pandas-dev/pandas   
16  https://api.github.com/repos/pandas-dev/pandas   
17  https://api.github.com/repos/pandas-dev/pandas   
18  https://api.github.com/repos/pandas-dev/pandas   
19  https://api.github.com/repos/pandas-dev/pandas   
20  https://api.github.com/repos/pandas-dev/pandas   
21  https://api.github.com/repos/pandas-dev/pandas   
22  https://api.github.com/repos/pandas-dev/pandas   
23  https://api.github.com/repos/pandas-dev/pandas   
24  https://api.github.com/repos/pandas-dev/pandas   
25  https://api.github.com/repos/pandas-dev/pandas   
26  https://api.github.com/repos/pandas-dev/pandas   
27  https://api.github.com/repos/pandas-dev/pandas   
28  https://api.github.com/repos/pandas-dev/pandas   
29  https://api.github.com/repos/pandas-dev/pandas   

                                           labels_url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com/repos/pandas-dev/pandas...   
3   https://api.github.com/repos/pandas-dev/pandas...   
4   https://api.github.com/repos/pandas-dev/pandas...   
5   https://api.github.com/repos/pandas-dev/pandas...   
6   https://api.github.com/repos/pandas-dev/pandas...   
7   https://api.github.com/repos/pandas-dev/pandas...   
8   https://api.github.com/repos/pandas-dev/pandas...   
9   https://api.github.com/repos/pand

## Step 1. Load RAW JSON

In [93]:
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [95]:
data = requests.get(url)

<It is a success response code! [200]>

In [96]:
data

<Response [200]>

This data which we have recieved through our request is in a response object 'data'. We need to convert this response object into RAW json

Let's convert it to json!

In [97]:
data1 = data.json()

In [98]:
data1                          # data in RAW format, output as a list [ ]

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51985',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51985/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51985/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51985/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51985',
  'id': 1625482360,
  'node_id': 'PR_kwDOAA0YD85MGq1g',
  'number': 51985,
  'title': 'BUG: Add numpy_nullable support to arrow csv parser',
  'user': {'login': 'phofl',
   'id': 61934744,
   'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/phofl',
   'html_url': 'https://github.com/phofl',
   'followers_url': 'https://api.github.com/users/phofl/followers',
   'following_url': 'https://api.github.com

RAW JSON is available (data1) but the output comes in a list [ ]

In [99]:
type(data1)

list

In [100]:
len(data1)

30

There are 30 unique dictionaries!

Q. Find 'user_id' from 1 single dictionary.

Step 1. Fetching the first dictionary...

In [101]:
data1[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51985',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51985/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51985/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51985/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/51985',
 'id': 1625482360,
 'node_id': 'PR_kwDOAA0YD85MGq1g',
 'number': 51985,
 'title': 'BUG: Add numpy_nullable support to arrow csv parser',
 'user': {'login': 'phofl',
  'id': 61934744,
  'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
  'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/phofl',
  'html_url': 'https://github.com/phofl',
  'followers_url': 'https://api.github.com/users/phofl/followers',
  'following_url': 'https://api.github.com/users/phofl/follow

Step 2. Fetching 'user'

In [102]:
data1[0]['user']

{'login': 'phofl',
 'id': 61934744,
 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/phofl',
 'html_url': 'https://github.com/phofl',
 'followers_url': 'https://api.github.com/users/phofl/followers',
 'following_url': 'https://api.github.com/users/phofl/following{/other_user}',
 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions',
 'organizations_url': 'https://api.github.com/users/phofl/orgs',
 'repos_url': 'https://api.github.com/users/phofl/repos',
 'events_url': 'https://api.github.com/users/phofl/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/phofl/received_events',
 'type': 'User',
 'site_admin': False}

Step 3. Fetch id

In [103]:
data1[0]['user']['id']

61934744

Done!

Now Get the user_id from all 30 Dictionaries...


In [105]:

for i in range(len(data1)):
    print(data1[i]['user']['id'])                           
    

61934744
35164941
2395780
38412262
26364415
8078968
26364415
61934744
82477528
8078968
39696536
47963215
38412262
8078968
8078968
15380498
61934744
20811121
77875500
38412262
45562402
53919701
61934744
124939984
1020496
9269985
14967061
11656932
26364415
91160475


Present the 'url','repository_url','labels_url' data in a tabular format:

In [108]:
pd.DataFrame(data1, columns=['id','url','repository_url','labels_url','user'])

id                                                url  \
0   1625482360  https://api.github.com/repos/pandas-dev/pandas...   
1   1624807432  https://api.github.com/repos/pandas-dev/pandas...   
2   1624722607  https://api.github.com/repos/pandas-dev/pandas...   
3   1624660760  https://api.github.com/repos/pandas-dev/pandas...   
4   1624643510  https://api.github.com/repos/pandas-dev/pandas...   
5   1624613793  https://api.github.com/repos/pandas-dev/pandas...   
6   1624610753  https://api.github.com/repos/pandas-dev/pandas...   
7   1624541267  https://api.github.com/repos/pandas-dev/pandas...   
8   1624470590  https://api.github.com/repos/pandas-dev/pandas...   
9   1624371900  https://api.github.com/repos/pandas-dev/pandas...   
10  1624353854  https://api.github.com/repos/pandas-dev/pandas...   
11  1624343427  https://api.github.com/repos/pandas-dev/pandas...   
12  1624305806  https://api.github.com/repos/pandas-dev/pandas...   
13  1624130670  https://api.github.com/repos/pandas-dev/pandas...   
14  1624116915  https://api.github.com/repos/pandas-dev/pandas...   
15  1623963220  https://api.github.com/repos/pandas-dev/pandas...   
16  1623727368  https://api.github.com/repos/pandas-dev/pandas...   
17  1623323719  https://api.github.com/repos/pandas-dev/pandas...   
18  1623195150  https://api.github.com/repos/pandas-dev/pandas...   
19  1622718105  https://api.github.com/repos/pandas-dev/pandas...   
20  1622523653  https://api.github.com/repos/pandas-dev/pandas...   
21  1622468791  https://api.github.com/repos/pandas-dev/pandas...   
22  1622446958  https://api.github.com/repos/pandas-dev/pandas...   
23  1622428350  https://api.github.com/repos/pandas-dev/pandas...   
24  1622397176  https://api.github.com/repos/pandas-dev/pandas...   
25  1622337912  https://api.github.com/repos/pandas-dev/pandas...   
26  1622311561  https://api.github.com/repos/pandas-dev/pandas...   
27  1622301172  https://api.github.com/repos/pandas-dev/pandas...   
28  1622083362  https://api.github.com/repos/pandas-dev/pandas...   
29  1621825421  https://api.github.com/repos/pandas-dev/pandas...   

                                    repository_url  \
0   https://api.github.com/repos/pandas-dev/pandas   
1   https://api.github.com/repos/pandas-dev/pandas   
2   https://api.github.com/repos/pandas-dev/pandas   
3   https://api.github.com/repos/pandas-dev/pandas   
4   https://api.github.com/repos/pandas-dev/pandas   
5   https://api.github.com/repos/pandas-dev/pandas   
6   https://api.github.com/repos/pandas-dev/pandas   
7   https://api.github.com/repos/pandas-dev/pandas   
8   https://api.github.com/repos/pandas-dev/pandas   
9   https://api.github.com/repos/pandas-dev/pandas   
10  https://api.github.com/repos/pandas-dev/pandas   
11  https://api.github.com/repos/pandas-dev/pandas   
12  https://api.github.com/repos/pandas-dev/pandas   
13  https://api.github.com/repos/pandas-dev/pandas   
14  https://api.github.com/repos/pandas-dev/pandas   
15  https://api.github.com/repos/pandas-dev/pandas   
16  https://api.github.com/repos/pandas-dev/pandas   
17  https://api.github.com/repos/pandas-dev/pandas   
18  https://api.github.com/repos/pandas-dev/pandas   
19  https://api.github.com/repos/pandas-dev/pandas   
20  https://api.github.com/repos/pandas-dev/pandas   
21  https://api.github.com/repos/pandas-dev/pandas   
22  https://api.github.com/repos/pandas-dev/pandas   
23  https://api.github.com/repos/pandas-dev/pandas   
24  https://api.github.com/repos/pandas-dev/pandas   
25  https://api.github.com/repos/pandas-dev/pandas   
26  https://api.github.com/repos/pandas-dev/pandas   
27  https://api.github.com/repos/pandas-dev/pandas   
28  https://api.github.com/repos/pandas-dev/pandas   
29  https://api.github.com/repos/pandas-dev/pandas   

                                           labels_url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com

Now I wanna Save it!

In [109]:
df2 = pd.DataFrame(data1, columns=['id','url','repository_url','labels_url','user'])

In [110]:
df2.to_csv('test_json_res.csv')

In [111]:
ls

 Volume in drive C is OS
 Volume Serial Number is 1600-9EB4

 Directory of C:\Users\santa

15-03-2023  21:26    <DIR>          .
22-09-2022  14:03    <DIR>          ..
22-08-2022  12:19    <DIR>          .anaconda
08-02-2023  16:31    <DIR>          .conda
22-08-2022  12:19                25 .condarc
22-08-2022  12:18    <DIR>          .continuum
07-03-2023  12:25                58 .gitconfig
20-02-2023  11:11                53 .git-for-windows-updater
10-07-2022  18:25    <DIR>          .idlerc
15-03-2023  15:10    <DIR>          .ipynb_checkpoints
22-08-2022  13:10    <DIR>          .ipython
22-08-2022  14:04    <DIR>          .jupyter
14-03-2023  12:17    <DIR>          .matplotlib
27-08-2022  08:26                43 .python_history
27-02-2023  14:06               527 .vivaldi_reporting_data
04-01-2023  10:28    <DIR>          .vscode
17-02-2023  14:53    <DIR>          __pycache__
14-03-2023  12:07             1,173 addresses.csv
14-03-2023  12:55            32,256 airline1.xls
18-

## Task: Flatten the user data

In [127]:
for i in list(df2['user']):
                      #df3 = df2(['user'][i])
            df3 = i          #print(df3)
            print(df3)
                      


{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}
{'login': 'liang3zy22', 'id': 35164941, 'node_id': 'MDQ6VXNlcjM1MTY0OTQx', 'avatar_url': 'htt

In [128]:
df3.to_csv('test_json_res.csv')

AttributeError: 'dict' object has no attribute 'to_csv'

## [LIVE: 27th Jan Class on Pandas]

In [1]:
import pandas as pd

In [7]:
pd.read_csv("addresses.csv")

id  location_id                   address_1  address_2  \
0    1            1       2600 Middlefield Road        NaN   
1    2            2            24 Second Avenue        NaN   
2    3            3            24 Second Avenue        NaN   
3    4            4            24 Second Avenue        NaN   
4    5            5            24 Second Avenue        NaN   
5    6            6           800 Middle Avenue        NaN   
6    7            7              500 Arbor Road        NaN   
7    8            8           800 Middle Avenue        NaN   
8    9            9       2510 Middlefield Road        NaN   
9   10           10       1044 Middlefield Road        NaN   
10  11           11         2140 Euclid Avenue.        NaN   
11  12           12       1044 Middlefield Road  2nd Floor   
12  13           13         399 Marine Parkway.        NaN   
13  14           14          660 Veterans Blvd.        NaN   
14  15           15        1500 Valencia Street        NaN   
15  16           16         1161 South Bernardo        NaN   
16  17           17     409 South Spruce Avenue        NaN   
17  18           18            114 Fifth Avenue        NaN   
18  19           19         19 West 39th Avenue        NaN   
19  20           21          123 El Camino Real        NaN   
20  21           22  2013 Avenue of the fellows  Suite 100   

                   city state_province postal_code country  
0          Redwood City             CA       94063      US  
1             San Mateo             CA       94401      US  
2             San Mateo             CA       94403      US  
3             San Mateo             CA       94401      US  
4             San Mateo             CA       94401      US  
5            Menlo Park             CA  94025-9881      US  
6            Menlo Park             CA       94025      US  
7            Menlo Park             CA  94025-9881      US  
8          Redwood City             CA       94063      US  
9          Redwood City             CA       94063      US  
10         Redwood City             CA       94061      US  
11         Redwood City             CA       94063      US  
12         Redwood City             CA       94065      US  
13         Redwood City             CA       94063      US  
14        San Francisco             CA       94110      US  
15            Sunnyvale             CA       94087      US  
16  South San Francisco             CA       94080      US  
17         Redwood City             CA       94063      US  
18            San Mateo             CA       94403      US  
19              Belmont             CA       94002      US  
20        San Francisco             CA       94103      US

In [5]:
data = pd.read_csv("addresses.csv")

In [6]:
type(data)

pandas.core.frame.DataFrame

In [8]:
data.head()                   # head gives first 5 lines with indexing.. 1st line is always a header

id  location_id              address_1 address_2          city  \
0   1            1  2600 Middlefield Road       NaN  Redwood City   
1   2            2       24 Second Avenue       NaN     San Mateo   
2   3            3       24 Second Avenue       NaN     San Mateo   
3   4            4       24 Second Avenue       NaN     San Mateo   
4   5            5       24 Second Avenue       NaN     San Mateo   

  state_province postal_code country  
0             CA       94063      US  
1             CA       94401      US  
2             CA       94403      US  
3             CA       94401      US  
4             CA       94401      US

In [9]:
data.head(6)           # 6 is the custom index value when required to access through indexing

id  location_id              address_1 address_2          city  \
0   1            1  2600 Middlefield Road       NaN  Redwood City   
1   2            2       24 Second Avenue       NaN     San Mateo   
2   3            3       24 Second Avenue       NaN     San Mateo   
3   4            4       24 Second Avenue       NaN     San Mateo   
4   5            5       24 Second Avenue       NaN     San Mateo   
5   6            6      800 Middle Avenue       NaN    Menlo Park   

  state_province postal_code country  
0             CA       94063      US  
1             CA       94401      US  
2             CA       94403      US  
3             CA       94401      US  
4             CA       94401      US  
5             CA  94025-9881      US

In [10]:
data.tail()          # tail gives last 5 rows

id  location_id                   address_1  address_2  \
16  17           17     409 South Spruce Avenue        NaN   
17  18           18            114 Fifth Avenue        NaN   
18  19           19         19 West 39th Avenue        NaN   
19  20           21          123 El Camino Real        NaN   
20  21           22  2013 Avenue of the fellows  Suite 100   

                   city state_province postal_code country  
16  South San Francisco             CA       94080      US  
17         Redwood City             CA       94063      US  
18            San Mateo             CA       94403      US  
19              Belmont             CA       94002      US  
20        San Francisco             CA       94103      US

In [11]:
data.tail(8)        # can also be used as indexing

id  location_id                   address_1  address_2  \
13  14           14          660 Veterans Blvd.        NaN   
14  15           15        1500 Valencia Street        NaN   
15  16           16         1161 South Bernardo        NaN   
16  17           17     409 South Spruce Avenue        NaN   
17  18           18            114 Fifth Avenue        NaN   
18  19           19         19 West 39th Avenue        NaN   
19  20           21          123 El Camino Real        NaN   
20  21           22  2013 Avenue of the fellows  Suite 100   

                   city state_province postal_code country  
13         Redwood City             CA       94063      US  
14        San Francisco             CA       94110      US  
15            Sunnyvale             CA       94087      US  
16  South San Francisco             CA       94080      US  
17         Redwood City             CA       94063      US  
18            San Mateo             CA       94403      US  
19              Belmont             CA       94002      US  
20        San Francisco             CA       94103      US

In [12]:
data.columns

Index(['id', 'location_id', 'address_1', 'address_2', 'city', 'state_province',
       'postal_code', 'country'],
      dtype='object')

In [13]:
list(data.columns)           # simply typecast datatype into a list

['id',
 'location_id',
 'address_1',
 'address_2',
 'city',
 'state_province',
 'postal_code',
 'country']

In [14]:
data.head(3)

id  location_id              address_1 address_2          city  \
0   1            1  2600 Middlefield Road       NaN  Redwood City   
1   2            2       24 Second Avenue       NaN     San Mateo   
2   3            3       24 Second Avenue       NaN     San Mateo   

  state_province postal_code country  
0             CA       94063      US  
1             CA       94401      US  
2             CA       94403      US

In [15]:
# i want only location_id and address 1 

data[['location_id','address_1']]       # pass the arguments in a list when multiple columns...

location_id                   address_1
0             1       2600 Middlefield Road
1             2            24 Second Avenue
2             3            24 Second Avenue
3             4            24 Second Avenue
4             5            24 Second Avenue
5             6           800 Middle Avenue
6             7              500 Arbor Road
7             8           800 Middle Avenue
8             9       2510 Middlefield Road
9            10       1044 Middlefield Road
10           11         2140 Euclid Avenue.
11           12       1044 Middlefield Road
12           13         399 Marine Parkway.
13           14          660 Veterans Blvd.
14           15        1500 Valencia Street
15           16         1161 South Bernardo
16           17     409 South Spruce Avenue
17           18            114 Fifth Avenue
18           19         19 West 39th Avenue
19           21          123 El Camino Real
20           22  2013 Avenue of the fellows

In [16]:
data['state_province']

0     CA
1     CA
2     CA
3     CA
4     CA
5     CA
6     CA
7     CA
8     CA
9     CA
10    CA
11    CA
12    CA
13    CA
14    CA
15    CA
16    CA
17    CA
18    CA
19    CA
20    CA
Name: state_province, dtype: object

In [17]:
data[['state_province']]

state_province
0              CA
1              CA
2              CA
3              CA
4              CA
5              CA
6              CA
7              CA
8              CA
9              CA
10             CA
11             CA
12             CA
13             CA
14             CA
15             CA
16             CA
17             CA
18             CA
19             CA
20             CA

#####  Difference  between passing the arguments as a list or as a single string? 

In [18]:
type(data['state_province'])                     # argument as a single string

pandas.core.series.Series

In [19]:
type(data[['state_province']])                   # argument as a list

pandas.core.frame.DataFrame

In [24]:
csvdata = pd.read_csv('mohit2.csv')

In [26]:
csvdata.head(2)

Ticket ID                           Subject  Status Priority Source Type  \
0     132792  Demotion of BDM's- Team Subhendu  Closed      Low  Email  NaN   
1     177692     Mapping of BDA || TNL21864505  Closed      Low  Email  NaN   

            Agent                        Group      Created time  \
0  mohit chandak1  Achieve, DB & LS Management  07-10-2021 14:01   
1  mohit chandak1                     No Group  25-11-2021 13:00   

        Due by Time  ... Every response status     Product FD Agent Name  \
0  08-10-2021 14:01  ...                   NaN  No Product           NaN   
1  24-12-2021 10:43  ...                   NaN  No Product           NaN   

  Coordination Team Agents AT Agents Note Assignment Mode  \
0                      NaN       NaN  NaN             NaN   
1                      NaN       NaN  NaN             NaN   

   Ticket Closure Mode         Full name                  Contact ID  
0                  NaN  Subhendu Chandra  subhendu.chandra@byjus.com  
1                  NaN     Subham Sharma     subham.sharma@byjus.com  

[2 rows x 36 columns]

In [32]:
# how to access data from different sheets in excel

pd.read_excel('airline1.xls',sheet_name="Sheet3")

1960.0000  5.5540     0.4410     0.3193     3.0890     1.4810   
0        1961      5.465      0.460     0.3079      3.122      1.736
1        1962      5.825      0.485     0.3783      3.184      1.926
2        1963      6.876      0.506     0.4180      3.263      2.041
3        1964      7.823      0.538     0.5163      3.412      1.997
4        1965      9.120      0.564     0.5879      3.623      2.257
5        1966     10.512      0.586     0.5369      4.074      2.742
6        1967     13.020      0.622     0.4443      4.710      3.564
7        1968     15.261      0.666     0.3052      5.217      4.767
8        1969     16.313      0.731     0.2332      5.569      6.511
9        1970     16.002      0.831     0.1883      5.495      7.627
10       1971     15.876      0.906     0.2023      5.334      8.673
11       1972     16.662      1.000     0.2506      5.345      8.331
12       1973     17.014      1.056     0.2668      5.662      8.557
13       1974     19.305      1.131     0.2664      5.729      9.508
14       1975     18.721      1.247     0.2301      5.722      9.062

In [ ]:
# How to manage the header because the dataset has no header: Press Shift + Tab and read documentation


pd.read_excel('airline1.xls',sheet_name="Sheet3",)



In [33]:
pd.read_excel('airline1.xls',sheet_name="Sheet3",header=None)  # header = None <-- problem solved!

0       1      2       3      4      5
0   1960   5.554  0.441  0.3193  3.089  1.481
1   1961   5.465  0.460  0.3079  3.122  1.736
2   1962   5.825  0.485  0.3783  3.184  1.926
3   1963   6.876  0.506  0.4180  3.263  2.041
4   1964   7.823  0.538  0.5163  3.412  1.997
5   1965   9.120  0.564  0.5879  3.623  2.257
6   1966  10.512  0.586  0.5369  4.074  2.742
7   1967  13.020  0.622  0.4443  4.710  3.564
8   1968  15.261  0.666  0.3052  5.217  4.767
9   1969  16.313  0.731  0.2332  5.569  6.511
10  1970  16.002  0.831  0.1883  5.495  7.627
11  1971  15.876  0.906  0.2023  5.334  8.673
12  1972  16.662  1.000  0.2506  5.345  8.331
13  1973  17.014  1.056  0.2668  5.662  8.557
14  1974  19.305  1.131  0.2664  5.729  9.508
15  1975  18.721  1.247  0.2301  5.722  9.062

In [34]:
# How to give own column name? Renaming a column...

pd.read_excel('airline1.xls',sheet_name="Sheet3",names=['a','b','c','d','e','f'])

a       b      c       d      e      f
0   1961   5.465  0.460  0.3079  3.122  1.736
1   1962   5.825  0.485  0.3783  3.184  1.926
2   1963   6.876  0.506  0.4180  3.263  2.041
3   1964   7.823  0.538  0.5163  3.412  1.997
4   1965   9.120  0.564  0.5879  3.623  2.257
5   1966  10.512  0.586  0.5369  4.074  2.742
6   1967  13.020  0.622  0.4443  4.710  3.564
7   1968  15.261  0.666  0.3052  5.217  4.767
8   1969  16.313  0.731  0.2332  5.569  6.511
9   1970  16.002  0.831  0.1883  5.495  7.627
10  1971  15.876  0.906  0.2023  5.334  8.673
11  1972  16.662  1.000  0.2506  5.345  8.331
12  1973  17.014  1.056  0.2668  5.662  8.557
13  1974  19.305  1.131  0.2664  5.729  9.508
14  1975  18.721  1.247  0.2301  5.722  9.062

In [35]:
# save data into file

data1=pd.read_excel('airline1.xls',sheet_name="Sheet3",names=['a','b','c','d','e','f'])

In [36]:
data1.to_csv('test10.csv')

In [37]:
f=open('test10.csv','r+')

In [38]:
f.read()

',a,b,c,d,e,f\n0,1961,5.465,0.46,0.3079,3.122,1.736\n1,1962,5.825,0.485,0.3783,3.184,1.926\n2,1963,6.876,0.506,0.418,3.263,2.041\n3,1964,7.823,0.538,0.5163,3.412,1.997\n4,1965,9.12,0.564,0.5879,3.623,2.257\n5,1966,10.512,0.586,0.5369,4.074,2.742\n6,1967,13.02,0.622,0.4443,4.71,3.564\n7,1968,15.261,0.666,0.3052,5.217,4.767\n8,1969,16.313,0.731,0.2332,5.569,6.511\n9,1970,16.002,0.831,0.1883,5.495,7.627\n10,1971,15.876,0.906,0.2023,5.334,8.673\n11,1972,16.662,1.0,0.2506,5.345,8.331\n12,1973,17.014,1.056,0.2668,5.662,8.557\n13,1974,19.305,1.131,0.2664,5.729,9.508\n14,1975,18.721,1.247,0.2301,5.722,9.062\n'

In [39]:
pd.read_csv('test10.csv')

Unnamed: 0     a       b      c       d      e      f
0            0  1961   5.465  0.460  0.3079  3.122  1.736
1            1  1962   5.825  0.485  0.3783  3.184  1.926
2            2  1963   6.876  0.506  0.4180  3.263  2.041
3            3  1964   7.823  0.538  0.5163  3.412  1.997
4            4  1965   9.120  0.564  0.5879  3.623  2.257
5            5  1966  10.512  0.586  0.5369  4.074  2.742
6            6  1967  13.020  0.622  0.4443  4.710  3.564
7            7  1968  15.261  0.666  0.3052  5.217  4.767
8            8  1969  16.313  0.731  0.2332  5.569  6.511
9            9  1970  16.002  0.831  0.1883  5.495  7.627
10          10  1971  15.876  0.906  0.2023  5.334  8.673
11          11  1972  16.662  1.000  0.2506  5.345  8.331
12          12  1973  17.014  1.056  0.2668  5.662  8.557
13          13  1974  19.305  1.131  0.2664  5.729  9.508
14          14  1975  18.721  1.247  0.2301  5.722  9.062

In [40]:
# How to avoid the index column??

data = pd.read_csv('test10.csv')



In [41]:
data.to_csv('test10.csv',index=False)

In [42]:
pd.read_csv('test10.csv')

Unnamed: 0     a       b      c       d      e      f
0            0  1961   5.465  0.460  0.3079  3.122  1.736
1            1  1962   5.825  0.485  0.3783  3.184  1.926
2            2  1963   6.876  0.506  0.4180  3.263  2.041
3            3  1964   7.823  0.538  0.5163  3.412  1.997
4            4  1965   9.120  0.564  0.5879  3.623  2.257
5            5  1966  10.512  0.586  0.5369  4.074  2.742
6            6  1967  13.020  0.622  0.4443  4.710  3.564
7            7  1968  15.261  0.666  0.3052  5.217  4.767
8            8  1969  16.313  0.731  0.2332  5.569  6.511
9            9  1970  16.002  0.831  0.1883  5.495  7.627
10          10  1971  15.876  0.906  0.2023  5.334  8.673
11          11  1972  16.662  1.000  0.2506  5.345  8.331
12          12  1973  17.014  1.056  0.2668  5.662  8.557
13          13  1974  19.305  1.131  0.2664  5.729  9.508
14          14  1975  18.721  1.247  0.2301  5.722  9.062

link not working... use raw!
# read data directly from web

In [46]:
pd.read_csv("https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv")

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [47]:
pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79   
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9   
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199   
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23   
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27   
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...   
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127   
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75   
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52   
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97   
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146   
 
      DRB  TRB

html reads only the tabular data in a html page. It also reads all the tables together and presents them as individual elements in a list

In [48]:
data2 = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

type(data2)

list

In [49]:
len(data2)          # number of tables in the list

1

In [50]:
data2[0]           # access the table using indexing function in a list

Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79   
1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9   
2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199   
3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23   
4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27   
..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...   
670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127   
671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75   
672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52   
673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97   
674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146   

     DRB  TRB  AST  STL BLK  TOV   PF   PTS  
0    222  301   68   27  22   60  147   398  
1     19   28   16   16   7   14   24    94  
2    324  523   66   38  86   99  222   537  
3     54   77   15    4   9    9   30    60  
4    220  247  129   41   7  116  167  1035  
..   ...  ...  ...  ...  ..  ...  ...   ...  
670  284  411  173  124  25  117  171  1071  
671  170  245  135   86  17   75  115   685  
672  114  166   38   38   8   42   56   386  
673  265  362  100   34  49   62  156   472  
674  319  465  113   18  52   76  205   833  

[675 rows x 30 columns]

In [51]:
# How to save this data into a excel file?

data2[0].to_excel('basketball.xlsx')

### Pandas : class 2 [live class]

In [2]:
import pandas as pd

In [3]:
# Data Loading

pd.read_csv("addresses.csv")



id  location_id                   address_1  address_2  \
0    1            1       2600 Middlefield Road        NaN   
1    2            2            24 Second Avenue        NaN   
2    3            3            24 Second Avenue        NaN   
3    4            4            24 Second Avenue        NaN   
4    5            5            24 Second Avenue        NaN   
5    6            6           800 Middle Avenue        NaN   
6    7            7              500 Arbor Road        NaN   
7    8            8           800 Middle Avenue        NaN   
8    9            9       2510 Middlefield Road        NaN   
9   10           10       1044 Middlefield Road        NaN   
10  11           11         2140 Euclid Avenue.        NaN   
11  12           12       1044 Middlefield Road  2nd Floor   
12  13           13         399 Marine Parkway.        NaN   
13  14           14          660 Veterans Blvd.        NaN   
14  15           15        1500 Valencia Street        NaN   
15  16           16         1161 South Bernardo        NaN   
16  17           17     409 South Spruce Avenue        NaN   
17  18           18            114 Fifth Avenue        NaN   
18  19           19         19 West 39th Avenue        NaN   
19  20           21          123 El Camino Real        NaN   
20  21           22  2013 Avenue of the fellows  Suite 100   

                   city state_province postal_code country  
0          Redwood City             CA       94063      US  
1             San Mateo             CA       94401      US  
2             San Mateo             CA       94403      US  
3             San Mateo             CA       94401      US  
4             San Mateo             CA       94401      US  
5            Menlo Park             CA  94025-9881      US  
6            Menlo Park             CA       94025      US  
7            Menlo Park             CA  94025-9881      US  
8          Redwood City             CA       94063      US  
9          Redwood City             CA       94063      US  
10         Redwood City             CA       94061      US  
11         Redwood City             CA       94063      US  
12         Redwood City             CA       94065      US  
13         Redwood City             CA       94063      US  
14        San Francisco             CA       94110      US  
15            Sunnyvale             CA       94087      US  
16  South San Francisco             CA       94080      US  
17         Redwood City             CA       94063      US  
18            San Mateo             CA       94403      US  
19              Belmont             CA       94002      US  
20        San Francisco             CA       94103      US

In [4]:
# Understanding the attributes

data = pd.read_csv("https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv")

In [57]:
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [58]:
data.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [59]:
# datatypes of every column

data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [61]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

when datatype = object; doesnot come under describe()


### How to get description of categorical data?

1. filter columns where datatype = object
2. .describe()

In [64]:
data[['Name','Sex','Ticket','Cabin','Embarked']].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

Advanced Version:

In [65]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [66]:
type(data.dtypes)

pandas.core.series.Series

In [67]:
data.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [68]:
#_Khela_:

data.dtypes[data.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [69]:
data.dtypes[data.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [70]:


data[data.dtypes[data.dtypes == "object"].index]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [71]:

data[data.dtypes[data.dtypes == "object"].index].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [72]:
# filter dataset where surviour = 0

data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [76]:
data["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [77]:
data["Survived"] == 0

0       True
1      False
2      False
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Survived, Length: 891, dtype: bool

In [78]:
data[data["Survived"] == 0]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
6              7         0       1                   McCarthy, Mr. Timothy J   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  
0      male  22.0      1      0        A/5 21171   7.2500   NaN        S  
4      male  35.0      0      0           373450   8.0500   NaN        S  
5      male   NaN      0      0           330877   8.4583   NaN        Q  
6      male  54.0      0      0            17463  51.8625   E46        S  
7      male   2.0      3      1           349909  21.0750   NaN        S  
..      ...   ...    ...    ...              ...      ...   ...      ...  
884    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5           382652  29.1250   NaN        Q  
886    male  27.0      0      0           211536  13.0000   NaN        S  
888  female   NaN      1      2       W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0           370376   7.7500   NaN        Q  

[549 rows x 12 columns]

In [6]:
data[(data['Survived'] == 0) & (data['Sex'] == 'male')]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
881          882         0       3              Markun, Mr. Johann  male   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
881  33.0      0      0            349257   7.8958   NaN        S  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
890  32.0      0      0            370376   7.7500   NaN        Q  

[468 rows x 12 columns]

In [7]:
len(data[(data['Survived'] == 0) & (data['Sex'] == 'male')])

468

In [8]:
len(data[(data['Survived'] == 0) & (data['Sex'] == 'female')])

81

In [9]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [11]:
len(data[data['Sex']=='male'])

577

In [12]:
# Find fare is maximum

data['Fare']


0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [13]:
data['Fare'] == max(data['Fare'])

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [14]:
data[data['Fare'] == max(data['Fare'])]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [16]:
data[data['Fare'] == max(data['Fare'])][['Name']]

Name
258                    Ward, Miss. Anna
679  Cardeza, Mr. Thomas Drake Martinez
737              Lesurer, Mr. Gustave J

In [17]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [22]:
data[data['Cabin'].isnull() == False]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[204 rows x 12 columns]

## How to extract Rows?

continued later....

### Day 2 Live Class

In [1]:
import pandas as pd

In [2]:
pd.read_csv("addresses.csv")

id  location_id                   address_1  address_2  \
0    1            1       2600 Middlefield Road        NaN   
1    2            2            24 Second Avenue        NaN   
2    3            3            24 Second Avenue        NaN   
3    4            4            24 Second Avenue        NaN   
4    5            5            24 Second Avenue        NaN   
5    6            6           800 Middle Avenue        NaN   
6    7            7              500 Arbor Road        NaN   
7    8            8           800 Middle Avenue        NaN   
8    9            9       2510 Middlefield Road        NaN   
9   10           10       1044 Middlefield Road        NaN   
10  11           11         2140 Euclid Avenue.        NaN   
11  12           12       1044 Middlefield Road  2nd Floor   
12  13           13         399 Marine Parkway.        NaN   
13  14           14          660 Veterans Blvd.        NaN   
14  15           15        1500 Valencia Street        NaN   
15  16           16         1161 South Bernardo        NaN   
16  17           17     409 South Spruce Avenue        NaN   
17  18           18            114 Fifth Avenue        NaN   
18  19           19         19 West 39th Avenue        NaN   
19  20           21          123 El Camino Real        NaN   
20  21           22  2013 Avenue of the fellows  Suite 100   

                   city state_province postal_code country  
0          Redwood City             CA       94063      US  
1             San Mateo             CA       94401      US  
2             San Mateo             CA       94403      US  
3             San Mateo             CA       94401      US  
4             San Mateo             CA       94401      US  
5            Menlo Park             CA  94025-9881      US  
6            Menlo Park             CA       94025      US  
7            Menlo Park             CA  94025-9881      US  
8          Redwood City             CA       94063      US  
9          Redwood City             CA       94063      US  
10         Redwood City             CA       94061      US  
11         Redwood City             CA       94063      US  
12         Redwood City             CA       94065      US  
13         Redwood City             CA       94063      US  
14        San Francisco             CA       94110      US  
15            Sunnyvale             CA       94087      US  
16  South San Francisco             CA       94080      US  
17         Redwood City             CA       94063      US  
18            San Mateo             CA       94403      US  
19              Belmont             CA       94002      US  
20        San Francisco             CA       94103      US

### Practice Problem:

Load data from gitHub (Titanic data)

In [3]:
import pandas as pd

In [4]:

data = pd.read_csv("https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv")

Understanding the attributes of the dataset:

In [4]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
data.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

Find the datatype of the columns.

In [6]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Find brief info about the data

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


#
1. Data has 891 rows/records indexed from 0 ---> 890.
2. Age has missing values/records.


Get a statistical description of the data

In [8]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

.describe only works on the numerical columns to give a statistical description of the data. What to do for categorical data?

To get a description of the categorical columns :-

1. Filter out the categorical columns or datatype = object
2. Add .describe()

In [10]:
data[['Name','Sex','Ticket','Cabin','Embarked']].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

How to automate this column selection process?

In [12]:
type(data.dtypes)

pandas.core.series.Series

We know Series is similar to a List! It has index names as the column names and their datatype as the data stored in those indexes!

In [13]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [15]:
data.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

Out of data.dtypes, we need only the records where data.dtypes == "object"

In [16]:
data.dtypes[data.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

We want a list of columns ....

In [17]:
type(data.dtypes[data.dtypes == "object"])

pandas.core.series.Series

And we know Series stores Column name as index name and the datatype as the corresponding data to the index.

In [18]:
data.dtypes[data.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

Pass this entire outcome through data[ ]

In [20]:
data[data.dtypes[data.dtypes == "object"].index]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

Whenever parameters are passed in a list, it will give a DataFrame!

The task was to filter out the columns from the data based on their datatype.
Here is the data for the column names with categorical value or dtype = object.

In [25]:
data.dtypes[data.dtypes == 'float64']

Age     float64
Fare    float64
dtype: object

We have to get only the index which holds the column names. Hence,

In [26]:
data.dtypes[data.dtypes == 'float64'].index       

Index(['Age', 'Fare'], dtype='object')

Pass it through the actual data[ ] for when parameters are passed in a list, it gives a DataFrame or a tabular format of required data!

In [28]:
data[data.dtypes[data.dtypes == 'float64'].index]

Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [30]:
type(data[data.dtypes[data.dtypes == 'float64'].index])

pandas.core.frame.DataFrame

In [31]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

#### Find data for survived = 0

In [46]:
data['Survived']==0

0       True
1      False
2      False
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Survived, Length: 891, dtype: bool

In [47]:
data[data['Survived']==0]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
6              7         0       1                   McCarthy, Mr. Timothy J   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  
0      male  22.0      1      0        A/5 21171   7.2500   NaN        S  
4      male  35.0      0      0           373450   8.0500   NaN        S  
5      male   NaN      0      0           330877   8.4583   NaN        Q  
6      male  54.0      0      0            17463  51.8625   E46        S  
7      male   2.0      3      1           349909  21.0750   NaN        S  
..      ...   ...    ...    ...              ...      ...   ...      ...  
884    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5           382652  29.1250   NaN        Q  
886    male  27.0      0      0           211536  13.0000   NaN        S  
888  female   NaN      1      2       W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0           370376   7.7500   NaN        Q  

[549 rows x 12 columns]

Find people who have died and was male.

In [49]:
data[['Survived','Sex']]

Survived     Sex
0           0    male
1           1  female
2           1  female
3           1  female
4           0    male
..        ...     ...
886         0    male
887         1  female
888         0  female
889         1    male
890         0    male

[891 rows x 2 columns]

In [55]:
data[(data['Survived']==0) & (data['Sex']=='male')]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
881          882         0       3              Markun, Mr. Johann  male   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
881  33.0      0      0            349257   7.8958   NaN        S  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
890  32.0      0      0            370376   7.7500   NaN        Q  

[468 rows x 12 columns]

In [56]:
data[(data['Survived']==0) & (data['Sex']=='male')].count()

PassengerId    468
Survived       468
Pclass         468
Name           468
Sex            468
Age            360
SibSp          468
Parch          468
Ticket         468
Fare           468
Cabin           62
Embarked       468
dtype: int64

In [57]:
len(data[(data['Survived']==0) & (data['Sex']=='male')])

468

In [58]:
len(data[(data['Survived']==0) & (data['Sex']=='female')])

81

In [59]:
len(data[(data['Survived']==1) & (data['Sex']=='female')])

233

In [61]:
len(data[(data['Survived']==1) & (data['Sex']=='male')])

109

## Out of 891 people, 468 Men & 81 Women Died!

### 109 Male & 233 Women Survived!

In [67]:
data['Sex'].value_counts()          # Group_by_count operation!

male      577
female    314
Name: Sex, dtype: int64

### No. of Females in the ship: 314

In [72]:
len(data[data['Sex']=='female'])

314

### No. of Males in the ship: 577

In [70]:
len(data[data['Sex']=='male'])

577

## Give the name of the person who has paid the highest fare?

In [78]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [86]:
max(data['Fare'])

512.3292

In [88]:
data[data['Fare']==max(data['Fare'])]       # selecting the max data from data['Fare'] column

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [89]:
data[data['Fare']==max(data['Fare'])]['Name'] #just gettin the 'Name' through separate filter function

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

Did they die or did they survive?

In [94]:
data[data['Fare']==max(data['Fare'])]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [99]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

No. of people who have recieved a Cabin?

In [106]:
data[['Cabin']].count()

Cabin    204
dtype: int64

In [110]:
len(data[data['Cabin'].isnull() == False] )

204

Within the whole data[Checking in data['Cabin'] where the value is not null OR isnull() == False]!

In [109]:
data[data['Cabin'].isnull() == False]     

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[204 rows x 12 columns]

Data for the passengers with Cabin

### Add a new column in the data

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv")

In [5]:
data['new_col']="sudh"

In [6]:
data                                     # new column created with data 'sudh'

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked new_col  
0        0         A/5 21171   7.2500   NaN        S    sudh  
1        0          PC 17599  71.2833   C85        C    sudh  
2        0  STON/O2. 3101282   7.9250   NaN        S    sudh  
3        0            113803  53.1000  C123        S    sudh  
4        0            373450   8.0500   NaN        S    sudh  
..     ...               ...      ...   ...      ...     ...  
886      0            211536  13.0000   NaN        S    sudh  
887      0            112053  30.0000   B42        S    sudh  
888      2        W./C. 6607  23.4500   NaN        S    sudh  
889      0            111369  30.0000  C148        C    sudh  
890      0            370376   7.7500   NaN        Q    sudh  

[891 rows x 13 columns]

### How to duplicate a column?

In [7]:
data['Name_new'] = data['Name']

In [8]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked new_col  \
0        0         A/5 21171   7.2500   NaN        S    sudh   
1        0          PC 17599  71.2833   C85        C    sudh   
2        0  STON/O2. 3101282   7.9250   NaN        S    sudh   
3        0            113803  53.1000  C123        S    sudh   
4        0            373450   8.0500   NaN        S    sudh   
..     ...               ...      ...   ...      ...     ...   
886      0            211536  13.0000   NaN        S    sudh   
887      0            112053  30.0000   B42        S    sudh   
888      2        W./C. 6607  23.4500   NaN        S    sudh   
889      0            111369  30.0000  C148        C    sudh   
890      0            370376   7.7500   NaN        Q    sudh   

                                              Name_new  
0                              Braund, Mr. Owen Harris  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                               Heikkinen, Miss. Laina  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                             Allen, Mr. William Henry  
..                                                 ...  
886                              Montvila, Rev. Juozas  
887                       Graham, Miss. Margaret Edith  
888           Johnston, Miss. Catherine Helen "Carrie"  
889                              Behr, Mr. Karl Howell  
890                                Dooley, Mr. Patrick  

[891 rows x 14 columns]

### Create a new column whose values are addition between age and class

In [9]:
data['age_cl_sum']= data['Age']+data['Pclass']

In [11]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked new_col  \
0      0  A/5 21171   7.2500   NaN        S    sudh   
1      0   PC 17599  71.2833   C85        C    sudh   

                                            Name_new  age_cl_sum  
0                            Braund, Mr. Owen Harris        25.0  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0

### How to delete columns?

In [12]:
data.drop('age_cl_sum')

KeyError: "['age_cl_sum'] not found in axis"

Axis = 0 == Row

Axis = 1 == Column

By default, the drop function takes Axis as 0. So change the Axis to 1 as we are operating on the columns.

In [13]:
data.drop('age_cl_sum',axis=1)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked new_col  \
0        0         A/5 21171   7.2500   NaN        S    sudh   
1        0          PC 17599  71.2833   C85        C    sudh   
2        0  STON/O2. 3101282   7.9250   NaN        S    sudh   
3        0            113803  53.1000  C123        S    sudh   
4        0            373450   8.0500   NaN        S    sudh   
..     ...               ...      ...   ...      ...     ...   
886      0            211536  13.0000   NaN        S    sudh   
887      0            112053  30.0000   B42        S    sudh   
888      2        W./C. 6607  23.4500   NaN        S    sudh   
889      0            111369  30.0000  C148        C    sudh   
890      0            370376   7.7500   NaN        Q    sudh   

                                              Name_new  
0                              Braund, Mr. Owen Harris  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                               Heikkinen, Miss. Laina  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                             Allen, Mr. William Henry  
..                                                 ...  
886                              Montvila, Rev. Juozas  
887                       Graham, Miss. Margaret Edith  
888           Johnston, Miss. Catherine Helen "Carrie"  
889                              Behr, Mr. Karl Howell  
890                                Dooley, Mr. Patrick  

[891 rows x 14 columns]

In [14]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked new_col  \
0      0  A/5 21171   7.2500   NaN        S    sudh   
1      0   PC 17599  71.2833   C85        C    sudh   

                                            Name_new  age_cl_sum  
0                            Braund, Mr. Owen Harris        25.0  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0

The column was dropped Not DELETED!

inplace: By default Set to False --> changes are temporary!

Hence, we need to change the parameter inplace: True to make the changes permanent!

In [15]:
data.drop('age_cl_sum',axis=1,inplace=True)

In [16]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked new_col  \
0      0  A/5 21171   7.2500   NaN        S    sudh   
1      0   PC 17599  71.2833   C85        C    sudh   

                                            Name_new  
0                            Braund, Mr. Owen Harris  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...

If we forget about the inplace, then save the temporary data in a separate variable to access that dataset!

# How to do Row Operations?

In [17]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked new_col  \
0      0  A/5 21171   7.2500   NaN        S    sudh   
1      0   PC 17599  71.2833   C85        C    sudh   

                                            Name_new  
0                            Braund, Mr. Owen Harris  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...

### Remove the Row using indexes

In [18]:
data.drop(0)

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked new_col  \
1        0          PC 17599  71.2833   C85        C    sudh   
2        0  STON/O2. 3101282   7.9250   NaN        S    sudh   
3        0            113803  53.1000  C123        S    sudh   
4        0            373450   8.0500   NaN        S    sudh   
5        0            330877   8.4583   NaN        Q    sudh   
..     ...               ...      ...   ...      ...     ...   
886      0            211536  13.0000   NaN        S    sudh   
887      0            112053  30.0000   B42        S    sudh   
888      2        W./C. 6607  23.4500   NaN        S    sudh   
889      0            111369  30.0000  C148        C    sudh   
890      0            370376   7.7500   NaN        Q    sudh   

                                              Name_new  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                               Heikkinen, Miss. Laina  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                             Allen, Mr. William Henry  
5                                     Moran, Mr. James  
..                                                 ...  
886                              Montvila, Rev. Juozas  
887                       Graham, Miss. Margaret Edith  
888           Johnston, Miss. Catherine Helen "Carrie"  
889                              Behr, Mr. Karl Howell  
890                                Dooley, Mr. Patrick  

[890 rows x 14 columns]

We have not lost index 0 data as inplace was by default set to False!

### Fetch Row number 2

In [20]:
data.iloc[1]

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
new_col                                                     sudh
Name_new       Cumings, Mrs. John Bradley (Florence Briggs Th...
Name: 1, dtype: object

iloc = integer location or indexed location (for the rows)

In [21]:
data.loc[1]

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
new_col                                                     sudh
Name_new       Cumings, Mrs. John Bradley (Florence Briggs Th...
Name: 1, dtype: object

.iloc and .loc giving the same result!

iloc always goes for the default inbuilt internal indexes.[index location or integer location]

loc goes after named indexes. or direct location!

Since no rows were deleted from the dataset permanently, both the indexes are same. If a row was deleted, the internal indexing mechanism of pandas would rearrange the indexing as 0,1,2... which would then differ from the named indexes which has been named by the user!

 If we delete the first record, iloc would become 0 for second record  but loc would remain as 1.

In [22]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked new_col  \
0      0  A/5 21171   7.2500   NaN        S    sudh   
1      0   PC 17599  71.2833   C85        C    sudh   

                                            Name_new  
0                            Braund, Mr. Owen Harris  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...

### Fetch records from index 2 --> 5

In [24]:
data.loc[2:5]

PassengerId  Survived  Pclass  \
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
2                        Heikkinen, Miss. Laina  female  26.0      0      0   
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   
5                              Moran, Mr. James    male   NaN      0      0   

             Ticket     Fare Cabin Embarked new_col  \
2  STON/O2. 3101282   7.9250   NaN        S    sudh   
3            113803  53.1000  C123        S    sudh   
4            373450   8.0500   NaN        S    sudh   
5            330877   8.4583   NaN        Q    sudh   

                                       Name_new  
2                        Heikkinen, Miss. Laina  
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                      Allen, Mr. William Henry  
5                              Moran, Mr. James

#### Fetch data for row index 101 to 106 and columns 'Survived' & 'Pclass'

In [26]:
data.loc[101:106,['Survived','Pclass']]

Survived  Pclass
101         0       3
102         0       1
103         0       3
104         0       3
105         0       3
106         1       3

In [27]:
data.loc[3:4,['Fare','Cabin','Embarked']]

Fare Cabin Embarked
3  53.10  C123        S
4   8.05   NaN        S

it works with .loc but not .iloc as loc works with named indexes but iloc only works with internal indexing,ie,0,1,2....

To use iloc, we cant use named indexes like 'Fare','Cabin','Embarked' but we have to use their corresponding default internal indexing of pandas in integers...

In [28]:
data.iloc[3:4,[9,10,11]]

Fare Cabin Embarked
3  53.1  C123        S

iloc worked!

In [34]:
data.iloc[:,[0,2]]

PassengerId  Pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
886          887       2
887          888       1
888          889       3
889          890       1
890          891       3

[891 rows x 2 columns]

In [37]:
data.iloc[[3,5],[0,1,2]]

PassengerId  Survived  Pclass
3            4         1       1
5            6         0       3

### Fetch all the records where Age > 35

In [38]:
data[data['Age']>35]

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
11            12         1       1   
13            14         0       3   
15            16         1       2   
..           ...       ...     ...   
865          866         1       2   
871          872         1       1   
873          874         0       3   
879          880         1       1   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
..                                                 ...     ...   ...    ...   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   

     Parch    Ticket     Fare Cabin Embarked new_col  \
1        0  PC 17599  71.2833   C85        C    sudh   
6        0     17463  51.8625   E46        S    sudh   
11       0    113783  26.5500  C103        S    sudh   
13       5    347082  31.2750   NaN        S    sudh   
15       0    248706  16.0000   NaN        S    sudh   
..     ...       ...      ...   ...      ...     ...   
865      0    236852  13.0000   NaN        S    sudh   
871      1     11751  52.5542   D35        S    sudh   
873      0    345765   9.0000   NaN        S    sudh   
879      1     11767  83.1583   C50        C    sudh   
885      5    382652  29.1250   NaN        Q    sudh   

                                              Name_new  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  
6                              McCarthy, Mr. Timothy J  
11                            Bonnell, Miss. Elizabeth  
13                         Andersson, Mr. Anders Johan  
15                    Hewlett, Mrs. (Mary D Kingcome)   
..                                                 ...  
865                           Bystrom, Mrs. (Karolina)  
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  
873                        Vander Cruyssen, Mr. Victor  
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  
885               Rice, Mrs. William (Margaret Norton)  

[217 rows x 14 columns]

In [40]:
data[data['Age']>35].count()

PassengerId    217
Survived       217
Pclass         217
Name           217
Sex            217
Age            217
SibSp          217
Parch          217
Ticket         217
Fare           217
Cabin           95
Embarked       215
new_col        217
Name_new       217
dtype: int64

Let's create a subset of the data... data1

In [5]:
data1 = data.iloc[1:10,[2,3,4,5,9,10]]                # BRACKETING TA KHEYAL RAKH!

In [6]:
data1

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male   NaN   
6       1                            McCarthy, Mr. Timothy J    male  54.0   
7       3                     Palsson, Master. Gosta Leonard    male   2.0   
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

      Fare Cabin  
1  71.2833   C85  
2   7.9250   NaN  
3  53.1000  C123  
4   8.0500   NaN  
5   8.4583   NaN  
6  51.8625   E46  
7  21.0750   NaN  
8  11.1333   NaN  
9  30.0708   NaN

#### Rename the Row indexes to 'NAMES'... RESET/SET INDEXES

In [47]:
data1.set_index('Name')        # inplace can be used!

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   
McCarthy, Mr. Timothy J                                  1    male  54.0   
Palsson, Master. Gosta Leonard                           3    male   2.0   
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)        3  female  27.0   
Nasser, Mrs. Nicholas (Adele Achem)                      2  female  14.0   

                                                       Fare Cabin  
Name                                                               
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  
Heikkinen, Miss. Laina                               7.9250   NaN  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  
Allen, Mr. William Henry                             8.0500   NaN  
Moran, Mr. James                                     8.4583   NaN  
McCarthy, Mr. Timothy J                             51.8625   E46  
Palsson, Master. Gosta Leonard                      21.0750   NaN  
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   11.1333   NaN  
Nasser, Mrs. Nicholas (Adele Achem)                 30.0708   NaN

### Drop all the records which have NaN or NULL Values

In [48]:
data1.dropna()              # by default axis = 0 = row

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
6       1                            McCarthy, Mr. Timothy J    male  54.0   

      Fare Cabin  
1  71.2833   C85  
3  53.1000  C123  
6  51.8625   E46

In [49]:
data1.dropna(axis=1)      # column with Null value dropped!

Pclass                                               Name     Sex     Fare
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  71.2833
2       3                             Heikkinen, Miss. Laina  female   7.9250
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  53.1000
4       3                           Allen, Mr. William Henry    male   8.0500
5       3                                   Moran, Mr. James    male   8.4583
6       1                            McCarthy, Mr. Timothy J    male  51.8625
7       3                     Palsson, Master. Gosta Leonard    male  21.0750
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  11.1333
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  30.0708

#### threshold

In [50]:
data1.dropna(axis=1,thresh=1)

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male   NaN   
6       1                            McCarthy, Mr. Timothy J    male  54.0   
7       3                     Palsson, Master. Gosta Leonard    male   2.0   
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

      Fare Cabin  
1  71.2833   C85  
2   7.9250   NaN  
3  53.1000  C123  
4   8.0500   NaN  
5   8.4583   NaN  
6  51.8625   E46  
7  21.0750   NaN  
8  11.1333   NaN  
9  30.0708   NaN

In [51]:
data1.dropna(axis=1,thresh=2)

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male   NaN   
6       1                            McCarthy, Mr. Timothy J    male  54.0   
7       3                     Palsson, Master. Gosta Leonard    male   2.0   
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

      Fare Cabin  
1  71.2833   C85  
2   7.9250   NaN  
3  53.1000  C123  
4   8.0500   NaN  
5   8.4583   NaN  
6  51.8625   E46  
7  21.0750   NaN  
8  11.1333   NaN  
9  30.0708   NaN

In [55]:
data1.dropna(axis=1,thresh=9)

Pclass                                               Name     Sex     Fare
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  71.2833
2       3                             Heikkinen, Miss. Laina  female   7.9250
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  53.1000
4       3                           Allen, Mr. William Henry    male   8.0500
5       3                                   Moran, Mr. James    male   8.4583
6       1                            McCarthy, Mr. Timothy J    male  51.8625
7       3                     Palsson, Master. Gosta Leonard    male  21.0750
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  11.1333
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  30.0708

Threshold is the minimum number of Non Null values which must be present. below that the table drops!

To make the modifications permanent, use the feature inplace = True!

### fillna(): To fill data in Null value positions

In [57]:
data1.fillna("sudh")

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male  sudh   
6       1                            McCarthy, Mr. Timothy J    male  54.0   
7       3                     Palsson, Master. Gosta Leonard    male   2.0   
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

      Fare Cabin  
1  71.2833   C85  
2   7.9250  sudh  
3  53.1000  C123  
4   8.0500  sudh  
5   8.4583  sudh  
6  51.8625   E46  
7  21.0750  sudh  
8  11.1333  sudh  
9  30.0708  sudh

In [58]:
data1.fillna(data1['Age'].mean())        # NA filled with average of age!

Pclass                                               Name     Sex     Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000   
2       3                             Heikkinen, Miss. Laina  female  26.000   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000   
4       3                           Allen, Mr. William Henry    male  35.000   
5       3                                   Moran, Mr. James    male  28.875   
6       1                            McCarthy, Mr. Timothy J    male  54.000   
7       3                     Palsson, Master. Gosta Leonard    male   2.000   
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000   
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.000   

      Fare   Cabin  
1  71.2833     C85  
2   7.9250  28.875  
3  53.1000    C123  
4   8.0500  28.875  
5   8.4583  28.875  
6  51.8625     E46  
7  21.0750  28.875  
8  11.1333  28.875  
9  30.0708  28.875

### Groupby

In [59]:
data1.groupby('Sex').count()

Pclass  Name  Age  Fare  Cabin
Sex                                   
female       5     5    5     5      2
male         4     4    3     4      1

In [72]:
data1.groupby('Sex').mean()['Age']

Sex
female    28.000000
male      30.333333
Name: Age, dtype: float64

##### Find revenue generated by male and female

In [73]:
data1.groupby('Sex').sum()['Fare']

Sex
female    173.5124
male       89.4458
Name: Fare, dtype: float64

Creating another subset data

In [7]:
data2 = data.iloc[0:4,0:5]

### Concatenation operation

In [8]:
pd.concat([data1,data2])

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male   NaN   
6       1                            McCarthy, Mr. Timothy J    male  54.0   
7       3                     Palsson, Master. Gosta Leonard    male   2.0   
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
0       3                            Braund, Mr. Owen Harris    male   NaN   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   NaN   
2       3                             Heikkinen, Miss. Laina  female   NaN   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN   

      Fare Cabin  PassengerId  Survived  
1  71.2833   C85          NaN       NaN  
2   7.9250   NaN          NaN       NaN  
3  53.1000  C123          NaN       NaN  
4   8.0500   NaN          NaN       NaN  
5   8.4583   NaN          NaN       NaN  
6  51.8625   E46          NaN       NaN  
7  21.0750   NaN          NaN       NaN  
8  11.1333   NaN          NaN       NaN  
9  30.0708   NaN          NaN       NaN  
0      NaN   NaN          1.0       0.0  
1      NaN   NaN          2.0       1.0  
2      NaN   NaN          3.0       1.0  
3      NaN   NaN          4.0       1.0

Axis = 0 ---> Row wise concatenation

In [9]:
pd.concat([data1,data2],axis = 1)       # Vertical

Pclass                                               Name     Sex   Age  \
1     1.0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2     3.0                             Heikkinen, Miss. Laina  female  26.0   
3     1.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4     3.0                           Allen, Mr. William Henry    male  35.0   
5     3.0                                   Moran, Mr. James    male   NaN   
6     1.0                            McCarthy, Mr. Timothy J    male  54.0   
7     3.0                     Palsson, Master. Gosta Leonard    male   2.0   
8     3.0  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9     2.0                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
0     NaN                                                NaN     NaN   NaN   

      Fare Cabin  PassengerId  Survived  Pclass  \
1  71.2833   C85          2.0       1.0     1.0   
2   7.9250   NaN          3.0       1.0     3.0   
3  53.1000  C123          4.0       1.0     1.0   
4   8.0500   NaN          NaN       NaN     NaN   
5   8.4583   NaN          NaN       NaN     NaN   
6  51.8625   E46          NaN       NaN     NaN   
7  21.0750   NaN          NaN       NaN     NaN   
8  11.1333   NaN          NaN       NaN     NaN   
9  30.0708   NaN          NaN       NaN     NaN   
0      NaN   NaN          1.0       0.0     3.0   

                                                Name     Sex  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  
2                             Heikkinen, Miss. Laina  female  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  
4                                                NaN     NaN  
5                                                NaN     NaN  
6                                                NaN     NaN  
7                                                NaN     NaN  
8                                                NaN     NaN  
9                                                NaN     NaN  
0                            Braund, Mr. Owen Harris    male

#### Divide the data in Pclass by 3

In [11]:
data1['Pclass']

1    1
2    3
3    1
4    3
5    3
6    1
7    3
8    3
9    2
Name: Pclass, dtype: int64

In [14]:
data1['new']=data1['Pclass']

In [15]:
data1.head(2)

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   

      Fare Cabin  new  
1  71.2833   C85    1  
2   7.9250   NaN    3

In [21]:
data['new'] = data1['Pclass'].apply(lambda x: x/3)

In [22]:
data1.head()

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male   NaN   

      Fare Cabin  new  
1  71.2833   C85    1  
2   7.9250   NaN    3  
3  53.1000  C123    1  
4   8.0500   NaN    3  
5   8.4583   NaN    3

In [19]:
data['new'] = data1['Pclass'].apply(lambda x: x/3)

### Applying an external function

In [23]:
def func1(x):
    return x/3

In [24]:
data1['new1']=data1['Pclass'].apply(func1)

In [25]:
data1

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male   NaN   
6       1                            McCarthy, Mr. Timothy J    male  54.0   
7       3                     Palsson, Master. Gosta Leonard    male   2.0   
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

      Fare Cabin  new      new1  
1  71.2833   C85    1  0.333333  
2   7.9250   NaN    3  1.000000  
3  53.1000  C123    1  0.333333  
4   8.0500   NaN    3  1.000000  
5   8.4583   NaN    3  1.000000  
6  51.8625   E46    1  0.333333  
7  21.0750   NaN    3  1.000000  
8  11.1333   NaN    3  1.000000  
9  30.0708   NaN    2  0.666667

### Create a more column in data2 to store len of their name

In [26]:
def length(x):
    a=len(x)
    return a

In [27]:
data2['len']=data2['Name'].apply(length)

data2

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex  len  
0                            Braund, Mr. Owen Harris    male   23  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   51  
2                             Heikkinen, Miss. Laina  female   22  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   44

wherever passengerid <3,keep data as it is, else update with log of data

In [28]:
import math
def cust1(x):
    if x<3:
        return x
    else:
        return math.log10(x)
    
    
data2['PassengerId']=data2['PassengerId'].apply(cust1)

data2

PassengerId  Survived  Pclass  \
0     1.000000         0       3   
1     2.000000         1       1   
2     0.477121         1       3   
3     0.602060         1       1   

                                                Name     Sex  len  
0                            Braund, Mr. Owen Harris    male   23  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   51  
2                             Heikkinen, Miss. Laina  female   22  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   44

### Change female = 1 , male =0

In [29]:
def test2(x):
    if x=='female':
        return 1
    else:
        return 0
    
data2['Sex']=data2['Sex'].apply(test2)

data2

PassengerId  Survived  Pclass  \
0     1.000000         0       3   
1     2.000000         1       1   
2     0.477121         1       3   
3     0.602060         1       1   

                                                Name  Sex  len  
0                            Braund, Mr. Owen Harris    0   23  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1   51  
2                             Heikkinen, Miss. Laina    1   22  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1   44

In [30]:
data.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked       new  
0      0         A/5 21171   7.2500   NaN        S       NaN  
1      0          PC 17599  71.2833   C85        C  0.333333  
2      0  STON/O2. 3101282   7.9250   NaN        S  1.000000

### Fill NaN VALUE IN 'AGE' COLUMN TO AVERAGE VALUE OF AGE

# Pandas: DataAnalysis 1 [RECORDED]

In [31]:
import pandas as pd

In [32]:
ls

 Volume in drive C is OS
 Volume Serial Number is 1600-9EB4

 Directory of C:\Users\santa

17-03-2023  13:37    <DIR>          .
22-09-2022  14:03    <DIR>          ..
22-08-2022  12:19    <DIR>          .anaconda
08-02-2023  16:31    <DIR>          .conda
22-08-2022  12:19                25 .condarc
22-08-2022  12:18    <DIR>          .continuum
07-03-2023  12:25                58 .gitconfig
20-02-2023  11:11                53 .git-for-windows-updater
10-07-2022  18:25    <DIR>          .idlerc
15-03-2023  15:10    <DIR>          .ipynb_checkpoints
22-08-2022  13:10    <DIR>          .ipython
22-08-2022  14:04    <DIR>          .jupyter
14-03-2023  12:17    <DIR>          .matplotlib
27-08-2022  08:26                43 .python_history
27-02-2023  14:06               527 .vivaldi_reporting_data
04-01-2023  10:28    <DIR>          .vscode
17-02-2023  14:53    <DIR>          __pycache__
14-03-2023  12:07             1,173 addresses.csv
14-03-2023  12:55            32,256 airline1.xls
17-

# TITANIC

In [97]:
import pandas as pd
data = pd.read_csv("https://gist.githubusercontent.com/fyyying/4aa5b471860321d7b47fd881898162b7/raw/6907bb3a38bfbb6fccf3a8b1edfb90e39714d14f/titanic_dataset.csv")

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [5]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [7]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

1. age has missing values which needs to be handled.
2. Huge variation(std) in fare. 
3. Min Fare = 0
4. Min Age = 0.42(infant)

In [8]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
data.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [15]:
data.dtypes[data.dtypes == 'object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [16]:
data.dtypes[data.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [17]:
col_name = data.dtypes[data.dtypes == 'object'].index

In [18]:
col_name

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [20]:
data[col_name]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [21]:
data[col_name].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [14]:
data[['Name','Sex','Ticket','Cabin','Embarked']].describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [22]:
data['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [23]:
data['Name'][0:15]

0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
11                             Bonnell, Miss. Elizabeth
12                       Saundercock, Mr. William Henry
13                          Andersson, Mr. Anders Johan
14                 Vestrom, Miss. Hulda Amanda Adolfina
Name: Name, dtype: object

In [24]:
data['Name'][15:0:-1]

15                     Hewlett, Mrs. (Mary D Kingcome) 
14                 Vestrom, Miss. Hulda Amanda Adolfina
13                          Andersson, Mr. Anders Johan
12                       Saundercock, Mr. William Henry
11                             Bonnell, Miss. Elizabeth
10                      Sandstrom, Miss. Marguerite Rut
9                   Nasser, Mrs. Nicholas (Adele Achem)
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
7                        Palsson, Master. Gosta Leonard
6                               McCarthy, Mr. Timothy J
5                                      Moran, Mr. James
4                              Allen, Mr. William Henry
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
2                                Heikkinen, Miss. Laina
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
Name: Name, dtype: object

In [27]:
data[data['Age'].isnull()==True]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [30]:
ind_x = data[data['Age'].isnull()==True].index

In [29]:
len(data[data['Age'].isnull()==True])

177

In [31]:
data.loc[ind_x]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [34]:
data[data['Fare']== max(data['Fare'])]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

1. How many male and female passenger boarded.
2. how many survived.
3. how many casuality.
4. Name of eldest person.
5. how many passengers in 1st,2nd and 3rd class.
6. person whose name starts with "s".
7. Try to create a new column which is a summation of 'SibSp' and "parch"
8. person below age 35
9. person died whose age less than 40
10. from cabin column separate text and numeric value.

In [50]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [51]:
#1.

data["Sex"].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [52]:
len(data[data["Sex"]=='male'])

577

In [55]:
data.groupby('Sex')['Sex'].count()

Sex
female    314
male      577
Name: Sex, dtype: int64

In [56]:
#2.
data["Survived"].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [63]:
len(data[data["Survived"]==1])

342

In [65]:
#3.

len(data[data['Survived']==0])

549

In [81]:
#4.

data[data['Age'] == data['Age'].max()]['Name']


0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [82]:
#5.

data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [83]:
data.groupby('Pclass')['Pclass'].count()

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64

In [91]:
#6.

len(data[data['Name'].str.startswith("S")])

86

In [99]:
#8.

len(data[data['Age'] < 25.0])


278

In [100]:
#9.

len(data[(data['Survived']==0) & (data['Age']<40)])



322

In [101]:
#10.

data2 = pd.DataFrame(data.Cabin.str.split('([a-zA-z]+)([^a-zA-z]+)'))
data2

Cabin
0             NaN
1     [, C, 85, ]
2             NaN
3    [, C, 123, ]
4             NaN
..            ...
886           NaN
887   [, B, 42, ]
888           NaN
889  [, C, 148, ]
890           NaN

[891 rows x 1 columns]

In [105]:
data['Cabin_number'] = data['Cabin'].str.replace('([A-Za-z]+)'," ")

data['Cabin_letter'] = data['Cabin'].str.extract('([A-Za-z]+)')

C:\Users\santa\AppData\Local\Temp\ipykernel_11144\2582599266.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data['Cabin_number'] = data['Cabin'].str.replace('([A-Za-z]+)'," ")


In [106]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked Cabin_number Cabin_letter  
0      0  A/5 21171   7.2500   NaN        S          NaN          NaN  
1      0   PC 17599  71.2833   C85        C           85            C

## New Bank Data

In [107]:
df = pd.read_csv('bank.csv',sep=';')

1. How many campaign available in this dataset.
2. How many users do we have with housing and personal loan.
3. How many person do we have whose age is 60+.
4. In which month we have targetted most of the customer.
5. which mode of call is giving more result?
6. How many entrepreneurs do we have?
7. How many customers with negative balance?
8. Prepare a data based on education level.


In [108]:
df.head(2)

age         job  marital  education default  balance housing loan  \
0   30  unemployed  married    primary      no     1787      no   no   
1   33    services  married  secondary      no     4789     yes  yes   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no

In [110]:
len(df['campaign'].unique())

32

In [113]:
len(df[(df['housing'] == 'yes') & (df['loan']=='yes')])

406

In [116]:
len(df[df['age']>60])

127

In [119]:
#4.

df['month'].value_counts().index[0]

'may'

In [120]:
df['contact'].value_counts()

cellular     2896
unknown      1324
telephone     301
Name: contact, dtype: int64

In [122]:
df.groupby(['contact','y']).count()

age   job  marital  education  default  balance  housing  \
contact   y                                                                
cellular  no   2480  2480     2480       2480     2480     2480     2480   
          yes   416   416      416        416      416      416      416   
telephone no    257   257      257        257      257      257      257   
          yes    44    44       44         44       44       44       44   
unknown   no   1263  1263     1263       1263     1263     1263     1263   
          yes    61    61       61         61       61       61       61   

               loan   day  month  duration  campaign  pdays  previous  \
contact   y                                                             
cellular  no   2480  2480   2480      2480      2480   2480      2480   
          yes   416   416    416       416       416    416       416   
telephone no    257   257    257       257       257    257       257   
          yes    44    44     44        44        44     44        44   
unknown   no   1263  1263   1263      1263      1263   1263      1263   
          yes    61    61     61        61        61     61        61   

               poutcome  
contact   y              
cellular  no       2480  
          yes       416  
telephone no        257  
          yes        44  
unknown   no       1263  
          yes        61

In [123]:
df_groupby = df.groupby(['contact','y']).count()

In [126]:
df_groupby.loc['cellular','yes'][0]

416

In [127]:
len(df['job']=='entrepreneur')

4521

In [128]:
df[df.balance < 0]

age            job   marital  education default  balance housing loan  \
9      43       services   married    primary      no      -88     yes  yes   
18     25    blue-collar    single    primary      no     -221     yes   no   
48     32   entrepreneur    single    primary     yes     -849     yes  yes   
60     41    blue-collar   married    primary      no     -516      no  yes   
92     27       services    single  secondary      no     -195     yes   no   
...   ...            ...       ...        ...     ...      ...     ...  ...   
4474   44    blue-collar   married    primary      no     -237     yes   no   
4502   42       services   married  secondary      no      -91     yes  yes   
4506   42     unemployed  divorced   tertiary      no     -166      no   no   
4516   33       services   married  secondary      no     -333     yes   no   
4517   57  self-employed   married   tertiary     yes    -3313     yes  yes   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
9      cellular   17   apr       313         1    147         2  failure   no  
18      unknown   23   may       250         1     -1         0  unknown   no  
48     cellular    4   feb       204         1     -1         0  unknown   no  
60    telephone    8   jul       554         3     -1         0  unknown   no  
92     cellular   18   may       391         1     -1         0  unknown  yes  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
4474  telephone   10   jul        73         1     -1         0  unknown   no  
4502   cellular    5   feb        43         1     -1         0  unknown   no  
4506   cellular   29   aug        85         4     -1         0  unknown   no  
4516   cellular   30   jul       329         5     -1         0  unknown   no  
4517    unknown    9   may       153         1     -1         0  unknown   no  

[366 rows x 17 columns]

In [130]:
df['education'].unique()

array(['primary', 'secondary', 'tertiary', 'unknown'], dtype=object)

In [132]:

l=[]

for i in df['education'].unique():
    l.append(df[df['education'] ==i])
    
len(l)

4

In [133]:
l[0]

age            job   marital education default  balance housing loan  \
0      30     unemployed   married   primary      no     1787      no   no   
9      43       services   married   primary      no      -88     yes  yes   
18     25    blue-collar    single   primary      no     -221     yes   no   
26     55    blue-collar   married   primary      no      627     yes   no   
36     78        retired  divorced   primary      no      229      no   no   
...   ...            ...       ...       ...     ...      ...     ...  ...   
4480   23    blue-collar   married   primary      no     1158     yes   no   
4485   53    blue-collar   married   primary      no      238     yes   no   
4486   37    blue-collar   married   primary      no      378     yes   no   
4499   45    blue-collar  divorced   primary      no      942      no   no   
4503   60  self-employed   married   primary      no      362      no  yes   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   19   oct        79         1     -1         0  unknown   no  
9      cellular   17   apr       313         1    147         2  failure   no  
18      unknown   23   may       250         1     -1         0  unknown   no  
26      unknown    5   may       247         1     -1         0  unknown   no  
36    telephone   22   oct        97         1     -1         0  unknown  yes  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
4480   cellular   16   apr       743         1     -1         0  unknown   no  
4485   cellular   11   may       238         2    361         5  failure   no  
4486    unknown    9   may       514         1     -1         0  unknown   no  
4499   cellular   21   nov       362         1     -1         0  unknown   no  
4503   cellular   29   jul       816         6     -1         0  unknown  yes  

[678 rows x 17 columns]

In [134]:
l[1]

age          job  marital  education default  balance housing loan  \
1      33     services  married  secondary      no     4789     yes  yes   
4      59  blue-collar  married  secondary      no        0     yes   no   
7      39   technician  married  secondary      no      147     yes   no   
10     39     services  married  secondary      no     9374     yes   no   
11     43       admin.  married  secondary      no      264     yes   no   
...   ...          ...      ...        ...     ...      ...     ...  ...   
4514   38  blue-collar  married  secondary      no     1205     yes   no   
4515   32     services   single  secondary      no      473     yes   no   
4516   33     services  married  secondary      no     -333     yes   no   
4518   57   technician  married  secondary      no      295      no   no   
4519   28  blue-collar  married  secondary      no     1137      no   no   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
1     cellular   11   may       220         1    339         4  failure  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
7     cellular    6   may       151         2     -1         0  unknown  no  
10     unknown   20   may       273         1     -1         0  unknown  no  
11    cellular   17   apr       113         2     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4514  cellular   20   apr        45         4    153         1  failure  no  
4515  cellular    7   jul       624         5     -1         0  unknown  no  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  

[2306 rows x 17 columns]

In [135]:
l[2]

age            job   marital education default  balance housing loan  \
2      35     management    single  tertiary      no     1350     yes   no   
3      30     management   married  tertiary      no     1476     yes  yes   
5      35     management    single  tertiary      no      747      no   no   
6      36  self-employed   married  tertiary      no      307     yes   no   
8      41   entrepreneur   married  tertiary      no      221     yes   no   
...   ...            ...       ...       ...     ...      ...     ...  ...   
4501   34     management   married  tertiary      no      297     yes   no   
4506   42     unemployed  divorced  tertiary      no     -166      no   no   
4509   51     technician   married  tertiary      no     2506      no   no   
4517   57  self-employed   married  tertiary     yes    -3313     yes  yes   
4520   44   entrepreneur    single  tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
5     cellular   23   feb       141         2    176         3  failure  no  
6     cellular   14   may       341         1    330         2    other  no  
8      unknown   14   may        57         2     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4501  cellular   26   aug        63         4     -1         0  unknown  no  
4506  cellular   29   aug        85         4     -1         0  unknown  no  
4509  cellular   30   nov       210         3     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[1350 rows x 17 columns]

In [136]:
l[3]

age          job   marital education default  balance housing loan  \
20     38   management  divorced   unknown      no        0     yes   no   
27     67      retired   married   unknown      no      696      no   no   
49     61       admin.   married   unknown      no     4629     yes   no   
132    43  blue-collar   married   unknown     yes     -715     yes   no   
133    48       admin.   married   unknown      no        0     yes   no   
...   ...          ...       ...       ...     ...      ...     ...  ...   
4337   73      retired   married   unknown      no      519      no   no   
4342   50  blue-collar   married   unknown      no     2284     yes   no   
4428   48  blue-collar   married   unknown      no      439     yes   no   
4471   59   management   married   unknown      no     3534      no   no   
4508   42       admin.   married   unknown      no      642     yes  yes   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
20     cellular   18   nov        96         2     -1         0  unknown   no  
27    telephone   17   aug       119         1    105         2  failure   no  
49     cellular   27   jan       181         1     92         1  success  yes  
132     unknown   30   may        67         3     -1         0  unknown   no  
133    cellular    8   may        85         1    168         2  failure   no  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
4337  telephone   16   oct       434         1     57         1  failure  yes  
4342  telephone   31   jul      1088        17     -1         0  unknown  yes  
4428   cellular    2   feb       212         1    249         2    other   no  
4471   cellular   21   nov       216         4     -1         0  unknown   no  
4508    unknown   16   may       509         2     -1         0  unknown   no  

[187 rows x 17 columns]

### TASK

Read all the resume from inueron git in pdf,word, and create a dataframe with resume name as a index value, and column : emailid, linkdin id, git id, skills

# Live Class 3

In [5]:
d1 ={'key1':[1,2,3,4,5,6],
     'key2':[7,8,9,10,11,12],
     'key3':[13,14,15,16,17,18],
     'key4':[10,20,21,22,23,24]
    }

Convert the dictionary into pandas DataFrame

In [6]:
import pandas as pd

pd.DataFrame(d1)

key1  key2  key3  key4
0     1     7    13    10
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5     6    12    18    24

Number of values should be same for all the keys to convert it to a DataFrame. Arrays must be of the same length.

In [3]:
pd.DataFrame(d1,index=['a','b','c','d','e','f'])

key1  key2  key3  key4
a     1     7    13    10
b     2     8    14    20
c     3     9    15    21
d     4    10    16    22
e     5    11    17    23
f     6    12    18    24

In [7]:
d2 ={'key1':[1,2,3,4,5,"sudh"],
     'key2':[7,8,"kumar",10,11,12],
     'key3':[13,14,15,16,17,18],
     'key4':[10,20,21,"inueron","pwskills",24]
    }

In [8]:
pd.DataFrame(d2)

key1   key2  key3      key4
0     1      7    13        10
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   inueron
4     5     11    17  pwskills
5  sudh     12    18        24